#!/bin/bash

echo Generating ICNS file for mac...

rm -fr icon.iconset
mkdir icon.iconset
cd icon.iconset
convert -resize 16x16 ../icon_1024x1024.png icon_16x16.png
convert -resize 32x32 ../icon_1024x1024.png icon_16x16@2x.png
convert -resize 32x32 ../icon_1024x1024.png icon_32x32.png
convert -resize 64x64 ../icon_1024x1024.png icon_32x32@2x.png
convert -resize 128x128 ../icon_1024x1024.png icon_128x128.png
convert -resize 256x256 ../icon_1024x1024.png icon_128x128@2x.png
convert -resize 256x256 ../icon_1024x1024.png icon_256x256.png
convert -resize 512x512 ../icon_1024x1024.png icon_256x256@2x.png
convert -resize 512x512 ../icon_1024x1024.png icon_512x512.png
convert -resize 1024x1024 ../icon_1024x1024.png icon_512x512@2x.png
cd ..
iconutil -c icns icon.iconset
rm -fr icon.iconset

echo Generating ICO file for windows...

rm -f icon.ico
convert icon_1024x1024.png -define icon:auto-resize=64,48,32,16 icon.ico

echo Generating PNG file for linux...

rm -f icon.png
convert -resize 256x256 icon_1024x1024.png icon.png

echo Done
