/*
 * Copyright (c) 2020. Kin-Hong Wong. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/anchor_generator.proto

package object_detection.protos;

public final class AnchorGeneratorOuterClass {
  private AnchorGeneratorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnchorGeneratorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:object_detection.protos.AnchorGenerator)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
     * @return Whether the gridAnchorGenerator field is set.
     */
    boolean hasGridAnchorGenerator();
    /**
     * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
     * @return The gridAnchorGenerator.
     */
    object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator getGridAnchorGenerator();
    /**
     * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
     */
    object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGeneratorOrBuilder getGridAnchorGeneratorOrBuilder();

    /**
     * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
     * @return Whether the ssdAnchorGenerator field is set.
     */
    boolean hasSsdAnchorGenerator();
    /**
     * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
     * @return The ssdAnchorGenerator.
     */
    object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator getSsdAnchorGenerator();
    /**
     * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
     */
    object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGeneratorOrBuilder getSsdAnchorGeneratorOrBuilder();

    /**
     * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
     * @return Whether the multiscaleAnchorGenerator field is set.
     */
    boolean hasMultiscaleAnchorGenerator();
    /**
     * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
     * @return The multiscaleAnchorGenerator.
     */
    object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator getMultiscaleAnchorGenerator();
    /**
     * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
     */
    object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGeneratorOrBuilder getMultiscaleAnchorGeneratorOrBuilder();

    /**
     * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
     * @return Whether the flexibleGridAnchorGenerator field is set.
     */
    boolean hasFlexibleGridAnchorGenerator();
    /**
     * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
     * @return The flexibleGridAnchorGenerator.
     */
    object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator getFlexibleGridAnchorGenerator();
    /**
     * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
     */
    object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGeneratorOrBuilder getFlexibleGridAnchorGeneratorOrBuilder();

    public object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator.AnchorGeneratorOneofCase getAnchorGeneratorOneofCase();
  }
  /**
   * <pre>
   * Configuration proto for the anchor generator to use in the object detection
   * pipeline. See core/anchor_generator.py for details.
   * </pre>
   *
   * Protobuf type {@code object_detection.protos.AnchorGenerator}
   */
  public static final class AnchorGenerator extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:object_detection.protos.AnchorGenerator)
      AnchorGeneratorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AnchorGenerator.newBuilder() to construct.
    private AnchorGenerator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnchorGenerator() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AnchorGenerator();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AnchorGenerator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.Builder subBuilder = null;
              if (anchorGeneratorOneofCase_ == 1) {
                subBuilder = ((object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) anchorGeneratorOneof_).toBuilder();
              }
              anchorGeneratorOneof_ =
                  input.readMessage(object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) anchorGeneratorOneof_);
                anchorGeneratorOneof_ = subBuilder.buildPartial();
              }
              anchorGeneratorOneofCase_ = 1;
              break;
            }
            case 18: {
              object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.Builder subBuilder = null;
              if (anchorGeneratorOneofCase_ == 2) {
                subBuilder = ((object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator) anchorGeneratorOneof_).toBuilder();
              }
              anchorGeneratorOneof_ =
                  input.readMessage(object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator) anchorGeneratorOneof_);
                anchorGeneratorOneof_ = subBuilder.buildPartial();
              }
              anchorGeneratorOneofCase_ = 2;
              break;
            }
            case 26: {
              object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.Builder subBuilder = null;
              if (anchorGeneratorOneofCase_ == 3) {
                subBuilder = ((object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) anchorGeneratorOneof_).toBuilder();
              }
              anchorGeneratorOneof_ =
                  input.readMessage(object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) anchorGeneratorOneof_);
                anchorGeneratorOneof_ = subBuilder.buildPartial();
              }
              anchorGeneratorOneofCase_ = 3;
              break;
            }
            case 34: {
              object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.Builder subBuilder = null;
              if (anchorGeneratorOneofCase_ == 4) {
                subBuilder = ((object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator) anchorGeneratorOneof_).toBuilder();
              }
              anchorGeneratorOneof_ =
                  input.readMessage(object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator) anchorGeneratorOneof_);
                anchorGeneratorOneof_ = subBuilder.buildPartial();
              }
              anchorGeneratorOneofCase_ = 4;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return object_detection.protos.AnchorGeneratorOuterClass.internal_static_object_detection_protos_AnchorGenerator_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return object_detection.protos.AnchorGeneratorOuterClass.internal_static_object_detection_protos_AnchorGenerator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator.class, object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator.Builder.class);
    }

    private int bitField0_;
    private int anchorGeneratorOneofCase_ = 0;
    private java.lang.Object anchorGeneratorOneof_;
    public enum AnchorGeneratorOneofCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      GRID_ANCHOR_GENERATOR(1),
      SSD_ANCHOR_GENERATOR(2),
      MULTISCALE_ANCHOR_GENERATOR(3),
      FLEXIBLE_GRID_ANCHOR_GENERATOR(4),
      ANCHORGENERATORONEOF_NOT_SET(0);
      private final int value;
      private AnchorGeneratorOneofCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static AnchorGeneratorOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static AnchorGeneratorOneofCase forNumber(int value) {
        switch (value) {
          case 1: return GRID_ANCHOR_GENERATOR;
          case 2: return SSD_ANCHOR_GENERATOR;
          case 3: return MULTISCALE_ANCHOR_GENERATOR;
          case 4: return FLEXIBLE_GRID_ANCHOR_GENERATOR;
          case 0: return ANCHORGENERATORONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public AnchorGeneratorOneofCase
    getAnchorGeneratorOneofCase() {
      return AnchorGeneratorOneofCase.forNumber(
          anchorGeneratorOneofCase_);
    }

    public static final int GRID_ANCHOR_GENERATOR_FIELD_NUMBER = 1;
    /**
     * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
     * @return Whether the gridAnchorGenerator field is set.
     */
    @java.lang.Override
    public boolean hasGridAnchorGenerator() {
      return anchorGeneratorOneofCase_ == 1;
    }
    /**
     * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
     * @return The gridAnchorGenerator.
     */
    @java.lang.Override
    public object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator getGridAnchorGenerator() {
      if (anchorGeneratorOneofCase_ == 1) {
         return (object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) anchorGeneratorOneof_;
      }
      return object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.getDefaultInstance();
    }
    /**
     * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
     */
    @java.lang.Override
    public object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGeneratorOrBuilder getGridAnchorGeneratorOrBuilder() {
      if (anchorGeneratorOneofCase_ == 1) {
         return (object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) anchorGeneratorOneof_;
      }
      return object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.getDefaultInstance();
    }

    public static final int SSD_ANCHOR_GENERATOR_FIELD_NUMBER = 2;
    /**
     * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
     * @return Whether the ssdAnchorGenerator field is set.
     */
    @java.lang.Override
    public boolean hasSsdAnchorGenerator() {
      return anchorGeneratorOneofCase_ == 2;
    }
    /**
     * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
     * @return The ssdAnchorGenerator.
     */
    @java.lang.Override
    public object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator getSsdAnchorGenerator() {
      if (anchorGeneratorOneofCase_ == 2) {
         return (object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator) anchorGeneratorOneof_;
      }
      return object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.getDefaultInstance();
    }
    /**
     * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
     */
    @java.lang.Override
    public object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGeneratorOrBuilder getSsdAnchorGeneratorOrBuilder() {
      if (anchorGeneratorOneofCase_ == 2) {
         return (object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator) anchorGeneratorOneof_;
      }
      return object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.getDefaultInstance();
    }

    public static final int MULTISCALE_ANCHOR_GENERATOR_FIELD_NUMBER = 3;
    /**
     * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
     * @return Whether the multiscaleAnchorGenerator field is set.
     */
    @java.lang.Override
    public boolean hasMultiscaleAnchorGenerator() {
      return anchorGeneratorOneofCase_ == 3;
    }
    /**
     * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
     * @return The multiscaleAnchorGenerator.
     */
    @java.lang.Override
    public object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator getMultiscaleAnchorGenerator() {
      if (anchorGeneratorOneofCase_ == 3) {
         return (object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) anchorGeneratorOneof_;
      }
      return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.getDefaultInstance();
    }
    /**
     * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
     */
    @java.lang.Override
    public object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGeneratorOrBuilder getMultiscaleAnchorGeneratorOrBuilder() {
      if (anchorGeneratorOneofCase_ == 3) {
         return (object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) anchorGeneratorOneof_;
      }
      return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.getDefaultInstance();
    }

    public static final int FLEXIBLE_GRID_ANCHOR_GENERATOR_FIELD_NUMBER = 4;
    /**
     * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
     * @return Whether the flexibleGridAnchorGenerator field is set.
     */
    @java.lang.Override
    public boolean hasFlexibleGridAnchorGenerator() {
      return anchorGeneratorOneofCase_ == 4;
    }
    /**
     * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
     * @return The flexibleGridAnchorGenerator.
     */
    @java.lang.Override
    public object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator getFlexibleGridAnchorGenerator() {
      if (anchorGeneratorOneofCase_ == 4) {
         return (object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator) anchorGeneratorOneof_;
      }
      return object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.getDefaultInstance();
    }
    /**
     * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
     */
    @java.lang.Override
    public object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGeneratorOrBuilder getFlexibleGridAnchorGeneratorOrBuilder() {
      if (anchorGeneratorOneofCase_ == 4) {
         return (object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator) anchorGeneratorOneof_;
      }
      return object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (anchorGeneratorOneofCase_ == 1) {
        output.writeMessage(1, (object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) anchorGeneratorOneof_);
      }
      if (anchorGeneratorOneofCase_ == 2) {
        output.writeMessage(2, (object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator) anchorGeneratorOneof_);
      }
      if (anchorGeneratorOneofCase_ == 3) {
        output.writeMessage(3, (object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) anchorGeneratorOneof_);
      }
      if (anchorGeneratorOneofCase_ == 4) {
        output.writeMessage(4, (object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator) anchorGeneratorOneof_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (anchorGeneratorOneofCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) anchorGeneratorOneof_);
      }
      if (anchorGeneratorOneofCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator) anchorGeneratorOneof_);
      }
      if (anchorGeneratorOneofCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) anchorGeneratorOneof_);
      }
      if (anchorGeneratorOneofCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator) anchorGeneratorOneof_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator)) {
        return super.equals(obj);
      }
      object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator other = (object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator) obj;

      if (!getAnchorGeneratorOneofCase().equals(other.getAnchorGeneratorOneofCase())) return false;
      switch (anchorGeneratorOneofCase_) {
        case 1:
          if (!getGridAnchorGenerator()
              .equals(other.getGridAnchorGenerator())) return false;
          break;
        case 2:
          if (!getSsdAnchorGenerator()
              .equals(other.getSsdAnchorGenerator())) return false;
          break;
        case 3:
          if (!getMultiscaleAnchorGenerator()
              .equals(other.getMultiscaleAnchorGenerator())) return false;
          break;
        case 4:
          if (!getFlexibleGridAnchorGenerator()
              .equals(other.getFlexibleGridAnchorGenerator())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (anchorGeneratorOneofCase_) {
        case 1:
          hash = (37 * hash) + GRID_ANCHOR_GENERATOR_FIELD_NUMBER;
          hash = (53 * hash) + getGridAnchorGenerator().hashCode();
          break;
        case 2:
          hash = (37 * hash) + SSD_ANCHOR_GENERATOR_FIELD_NUMBER;
          hash = (53 * hash) + getSsdAnchorGenerator().hashCode();
          break;
        case 3:
          hash = (37 * hash) + MULTISCALE_ANCHOR_GENERATOR_FIELD_NUMBER;
          hash = (53 * hash) + getMultiscaleAnchorGenerator().hashCode();
          break;
        case 4:
          hash = (37 * hash) + FLEXIBLE_GRID_ANCHOR_GENERATOR_FIELD_NUMBER;
          hash = (53 * hash) + getFlexibleGridAnchorGenerator().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration proto for the anchor generator to use in the object detection
     * pipeline. See core/anchor_generator.py for details.
     * </pre>
     *
     * Protobuf type {@code object_detection.protos.AnchorGenerator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:object_detection.protos.AnchorGenerator)
        object_detection.protos.AnchorGeneratorOuterClass.AnchorGeneratorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return object_detection.protos.AnchorGeneratorOuterClass.internal_static_object_detection_protos_AnchorGenerator_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return object_detection.protos.AnchorGeneratorOuterClass.internal_static_object_detection_protos_AnchorGenerator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator.class, object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator.Builder.class);
      }

      // Construct using object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        anchorGeneratorOneofCase_ = 0;
        anchorGeneratorOneof_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return object_detection.protos.AnchorGeneratorOuterClass.internal_static_object_detection_protos_AnchorGenerator_descriptor;
      }

      @java.lang.Override
      public object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator getDefaultInstanceForType() {
        return object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator.getDefaultInstance();
      }

      @java.lang.Override
      public object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator build() {
        object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator buildPartial() {
        object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator result = new object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (anchorGeneratorOneofCase_ == 1) {
          if (gridAnchorGeneratorBuilder_ == null) {
            result.anchorGeneratorOneof_ = anchorGeneratorOneof_;
          } else {
            result.anchorGeneratorOneof_ = gridAnchorGeneratorBuilder_.build();
          }
        }
        if (anchorGeneratorOneofCase_ == 2) {
          if (ssdAnchorGeneratorBuilder_ == null) {
            result.anchorGeneratorOneof_ = anchorGeneratorOneof_;
          } else {
            result.anchorGeneratorOneof_ = ssdAnchorGeneratorBuilder_.build();
          }
        }
        if (anchorGeneratorOneofCase_ == 3) {
          if (multiscaleAnchorGeneratorBuilder_ == null) {
            result.anchorGeneratorOneof_ = anchorGeneratorOneof_;
          } else {
            result.anchorGeneratorOneof_ = multiscaleAnchorGeneratorBuilder_.build();
          }
        }
        if (anchorGeneratorOneofCase_ == 4) {
          if (flexibleGridAnchorGeneratorBuilder_ == null) {
            result.anchorGeneratorOneof_ = anchorGeneratorOneof_;
          } else {
            result.anchorGeneratorOneof_ = flexibleGridAnchorGeneratorBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.anchorGeneratorOneofCase_ = anchorGeneratorOneofCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator) {
          return mergeFrom((object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator other) {
        if (other == object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator.getDefaultInstance()) return this;
        switch (other.getAnchorGeneratorOneofCase()) {
          case GRID_ANCHOR_GENERATOR: {
            mergeGridAnchorGenerator(other.getGridAnchorGenerator());
            break;
          }
          case SSD_ANCHOR_GENERATOR: {
            mergeSsdAnchorGenerator(other.getSsdAnchorGenerator());
            break;
          }
          case MULTISCALE_ANCHOR_GENERATOR: {
            mergeMultiscaleAnchorGenerator(other.getMultiscaleAnchorGenerator());
            break;
          }
          case FLEXIBLE_GRID_ANCHOR_GENERATOR: {
            mergeFlexibleGridAnchorGenerator(other.getFlexibleGridAnchorGenerator());
            break;
          }
          case ANCHORGENERATORONEOF_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int anchorGeneratorOneofCase_ = 0;
      private java.lang.Object anchorGeneratorOneof_;
      public AnchorGeneratorOneofCase
          getAnchorGeneratorOneofCase() {
        return AnchorGeneratorOneofCase.forNumber(
            anchorGeneratorOneofCase_);
      }

      public Builder clearAnchorGeneratorOneof() {
        anchorGeneratorOneofCase_ = 0;
        anchorGeneratorOneof_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator, object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.Builder, object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGeneratorOrBuilder> gridAnchorGeneratorBuilder_;
      /**
       * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
       * @return Whether the gridAnchorGenerator field is set.
       */
      @java.lang.Override
      public boolean hasGridAnchorGenerator() {
        return anchorGeneratorOneofCase_ == 1;
      }
      /**
       * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
       * @return The gridAnchorGenerator.
       */
      @java.lang.Override
      public object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator getGridAnchorGenerator() {
        if (gridAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 1) {
            return (object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) anchorGeneratorOneof_;
          }
          return object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.getDefaultInstance();
        } else {
          if (anchorGeneratorOneofCase_ == 1) {
            return gridAnchorGeneratorBuilder_.getMessage();
          }
          return object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
       */
      public Builder setGridAnchorGenerator(object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator value) {
        if (gridAnchorGeneratorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          anchorGeneratorOneof_ = value;
          onChanged();
        } else {
          gridAnchorGeneratorBuilder_.setMessage(value);
        }
        anchorGeneratorOneofCase_ = 1;
        return this;
      }
      /**
       * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
       */
      public Builder setGridAnchorGenerator(
          object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.Builder builderForValue) {
        if (gridAnchorGeneratorBuilder_ == null) {
          anchorGeneratorOneof_ = builderForValue.build();
          onChanged();
        } else {
          gridAnchorGeneratorBuilder_.setMessage(builderForValue.build());
        }
        anchorGeneratorOneofCase_ = 1;
        return this;
      }
      /**
       * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
       */
      public Builder mergeGridAnchorGenerator(object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator value) {
        if (gridAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 1 &&
              anchorGeneratorOneof_ != object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.getDefaultInstance()) {
            anchorGeneratorOneof_ = object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.newBuilder((object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) anchorGeneratorOneof_)
                .mergeFrom(value).buildPartial();
          } else {
            anchorGeneratorOneof_ = value;
          }
          onChanged();
        } else {
          if (anchorGeneratorOneofCase_ == 1) {
            gridAnchorGeneratorBuilder_.mergeFrom(value);
          }
          gridAnchorGeneratorBuilder_.setMessage(value);
        }
        anchorGeneratorOneofCase_ = 1;
        return this;
      }
      /**
       * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
       */
      public Builder clearGridAnchorGenerator() {
        if (gridAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 1) {
            anchorGeneratorOneofCase_ = 0;
            anchorGeneratorOneof_ = null;
            onChanged();
          }
        } else {
          if (anchorGeneratorOneofCase_ == 1) {
            anchorGeneratorOneofCase_ = 0;
            anchorGeneratorOneof_ = null;
          }
          gridAnchorGeneratorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
       */
      public object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.Builder getGridAnchorGeneratorBuilder() {
        return getGridAnchorGeneratorFieldBuilder().getBuilder();
      }
      /**
       * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
       */
      @java.lang.Override
      public object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGeneratorOrBuilder getGridAnchorGeneratorOrBuilder() {
        if ((anchorGeneratorOneofCase_ == 1) && (gridAnchorGeneratorBuilder_ != null)) {
          return gridAnchorGeneratorBuilder_.getMessageOrBuilder();
        } else {
          if (anchorGeneratorOneofCase_ == 1) {
            return (object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) anchorGeneratorOneof_;
          }
          return object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.GridAnchorGenerator grid_anchor_generator = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator, object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.Builder, object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGeneratorOrBuilder>
          getGridAnchorGeneratorFieldBuilder() {
        if (gridAnchorGeneratorBuilder_ == null) {
          if (!(anchorGeneratorOneofCase_ == 1)) {
            anchorGeneratorOneof_ = object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.getDefaultInstance();
          }
          gridAnchorGeneratorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator, object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.Builder, object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGeneratorOrBuilder>(
                  (object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) anchorGeneratorOneof_,
                  getParentForChildren(),
                  isClean());
          anchorGeneratorOneof_ = null;
        }
        anchorGeneratorOneofCase_ = 1;
        onChanged();;
        return gridAnchorGeneratorBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator, object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.Builder, object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGeneratorOrBuilder> ssdAnchorGeneratorBuilder_;
      /**
       * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
       * @return Whether the ssdAnchorGenerator field is set.
       */
      @java.lang.Override
      public boolean hasSsdAnchorGenerator() {
        return anchorGeneratorOneofCase_ == 2;
      }
      /**
       * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
       * @return The ssdAnchorGenerator.
       */
      @java.lang.Override
      public object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator getSsdAnchorGenerator() {
        if (ssdAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 2) {
            return (object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator) anchorGeneratorOneof_;
          }
          return object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.getDefaultInstance();
        } else {
          if (anchorGeneratorOneofCase_ == 2) {
            return ssdAnchorGeneratorBuilder_.getMessage();
          }
          return object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
       */
      public Builder setSsdAnchorGenerator(object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator value) {
        if (ssdAnchorGeneratorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          anchorGeneratorOneof_ = value;
          onChanged();
        } else {
          ssdAnchorGeneratorBuilder_.setMessage(value);
        }
        anchorGeneratorOneofCase_ = 2;
        return this;
      }
      /**
       * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
       */
      public Builder setSsdAnchorGenerator(
          object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.Builder builderForValue) {
        if (ssdAnchorGeneratorBuilder_ == null) {
          anchorGeneratorOneof_ = builderForValue.build();
          onChanged();
        } else {
          ssdAnchorGeneratorBuilder_.setMessage(builderForValue.build());
        }
        anchorGeneratorOneofCase_ = 2;
        return this;
      }
      /**
       * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
       */
      public Builder mergeSsdAnchorGenerator(object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator value) {
        if (ssdAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 2 &&
              anchorGeneratorOneof_ != object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.getDefaultInstance()) {
            anchorGeneratorOneof_ = object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.newBuilder((object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator) anchorGeneratorOneof_)
                .mergeFrom(value).buildPartial();
          } else {
            anchorGeneratorOneof_ = value;
          }
          onChanged();
        } else {
          if (anchorGeneratorOneofCase_ == 2) {
            ssdAnchorGeneratorBuilder_.mergeFrom(value);
          }
          ssdAnchorGeneratorBuilder_.setMessage(value);
        }
        anchorGeneratorOneofCase_ = 2;
        return this;
      }
      /**
       * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
       */
      public Builder clearSsdAnchorGenerator() {
        if (ssdAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 2) {
            anchorGeneratorOneofCase_ = 0;
            anchorGeneratorOneof_ = null;
            onChanged();
          }
        } else {
          if (anchorGeneratorOneofCase_ == 2) {
            anchorGeneratorOneofCase_ = 0;
            anchorGeneratorOneof_ = null;
          }
          ssdAnchorGeneratorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
       */
      public object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.Builder getSsdAnchorGeneratorBuilder() {
        return getSsdAnchorGeneratorFieldBuilder().getBuilder();
      }
      /**
       * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
       */
      @java.lang.Override
      public object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGeneratorOrBuilder getSsdAnchorGeneratorOrBuilder() {
        if ((anchorGeneratorOneofCase_ == 2) && (ssdAnchorGeneratorBuilder_ != null)) {
          return ssdAnchorGeneratorBuilder_.getMessageOrBuilder();
        } else {
          if (anchorGeneratorOneofCase_ == 2) {
            return (object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator) anchorGeneratorOneof_;
          }
          return object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.SsdAnchorGenerator ssd_anchor_generator = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator, object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.Builder, object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGeneratorOrBuilder>
          getSsdAnchorGeneratorFieldBuilder() {
        if (ssdAnchorGeneratorBuilder_ == null) {
          if (!(anchorGeneratorOneofCase_ == 2)) {
            anchorGeneratorOneof_ = object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.getDefaultInstance();
          }
          ssdAnchorGeneratorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator, object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator.Builder, object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGeneratorOrBuilder>(
                  (object_detection.protos.SsdAnchorGeneratorOuterClass.SsdAnchorGenerator) anchorGeneratorOneof_,
                  getParentForChildren(),
                  isClean());
          anchorGeneratorOneof_ = null;
        }
        anchorGeneratorOneofCase_ = 2;
        onChanged();;
        return ssdAnchorGeneratorBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator, object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.Builder, object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGeneratorOrBuilder> multiscaleAnchorGeneratorBuilder_;
      /**
       * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
       * @return Whether the multiscaleAnchorGenerator field is set.
       */
      @java.lang.Override
      public boolean hasMultiscaleAnchorGenerator() {
        return anchorGeneratorOneofCase_ == 3;
      }
      /**
       * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
       * @return The multiscaleAnchorGenerator.
       */
      @java.lang.Override
      public object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator getMultiscaleAnchorGenerator() {
        if (multiscaleAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 3) {
            return (object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) anchorGeneratorOneof_;
          }
          return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.getDefaultInstance();
        } else {
          if (anchorGeneratorOneofCase_ == 3) {
            return multiscaleAnchorGeneratorBuilder_.getMessage();
          }
          return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
       */
      public Builder setMultiscaleAnchorGenerator(object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator value) {
        if (multiscaleAnchorGeneratorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          anchorGeneratorOneof_ = value;
          onChanged();
        } else {
          multiscaleAnchorGeneratorBuilder_.setMessage(value);
        }
        anchorGeneratorOneofCase_ = 3;
        return this;
      }
      /**
       * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
       */
      public Builder setMultiscaleAnchorGenerator(
          object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.Builder builderForValue) {
        if (multiscaleAnchorGeneratorBuilder_ == null) {
          anchorGeneratorOneof_ = builderForValue.build();
          onChanged();
        } else {
          multiscaleAnchorGeneratorBuilder_.setMessage(builderForValue.build());
        }
        anchorGeneratorOneofCase_ = 3;
        return this;
      }
      /**
       * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
       */
      public Builder mergeMultiscaleAnchorGenerator(object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator value) {
        if (multiscaleAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 3 &&
              anchorGeneratorOneof_ != object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.getDefaultInstance()) {
            anchorGeneratorOneof_ = object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.newBuilder((object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) anchorGeneratorOneof_)
                .mergeFrom(value).buildPartial();
          } else {
            anchorGeneratorOneof_ = value;
          }
          onChanged();
        } else {
          if (anchorGeneratorOneofCase_ == 3) {
            multiscaleAnchorGeneratorBuilder_.mergeFrom(value);
          }
          multiscaleAnchorGeneratorBuilder_.setMessage(value);
        }
        anchorGeneratorOneofCase_ = 3;
        return this;
      }
      /**
       * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
       */
      public Builder clearMultiscaleAnchorGenerator() {
        if (multiscaleAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 3) {
            anchorGeneratorOneofCase_ = 0;
            anchorGeneratorOneof_ = null;
            onChanged();
          }
        } else {
          if (anchorGeneratorOneofCase_ == 3) {
            anchorGeneratorOneofCase_ = 0;
            anchorGeneratorOneof_ = null;
          }
          multiscaleAnchorGeneratorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
       */
      public object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.Builder getMultiscaleAnchorGeneratorBuilder() {
        return getMultiscaleAnchorGeneratorFieldBuilder().getBuilder();
      }
      /**
       * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
       */
      @java.lang.Override
      public object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGeneratorOrBuilder getMultiscaleAnchorGeneratorOrBuilder() {
        if ((anchorGeneratorOneofCase_ == 3) && (multiscaleAnchorGeneratorBuilder_ != null)) {
          return multiscaleAnchorGeneratorBuilder_.getMessageOrBuilder();
        } else {
          if (anchorGeneratorOneofCase_ == 3) {
            return (object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) anchorGeneratorOneof_;
          }
          return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.MultiscaleAnchorGenerator multiscale_anchor_generator = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator, object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.Builder, object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGeneratorOrBuilder>
          getMultiscaleAnchorGeneratorFieldBuilder() {
        if (multiscaleAnchorGeneratorBuilder_ == null) {
          if (!(anchorGeneratorOneofCase_ == 3)) {
            anchorGeneratorOneof_ = object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.getDefaultInstance();
          }
          multiscaleAnchorGeneratorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator, object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.Builder, object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGeneratorOrBuilder>(
                  (object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) anchorGeneratorOneof_,
                  getParentForChildren(),
                  isClean());
          anchorGeneratorOneof_ = null;
        }
        anchorGeneratorOneofCase_ = 3;
        onChanged();;
        return multiscaleAnchorGeneratorBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator, object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.Builder, object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGeneratorOrBuilder> flexibleGridAnchorGeneratorBuilder_;
      /**
       * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
       * @return Whether the flexibleGridAnchorGenerator field is set.
       */
      @java.lang.Override
      public boolean hasFlexibleGridAnchorGenerator() {
        return anchorGeneratorOneofCase_ == 4;
      }
      /**
       * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
       * @return The flexibleGridAnchorGenerator.
       */
      @java.lang.Override
      public object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator getFlexibleGridAnchorGenerator() {
        if (flexibleGridAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 4) {
            return (object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator) anchorGeneratorOneof_;
          }
          return object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.getDefaultInstance();
        } else {
          if (anchorGeneratorOneofCase_ == 4) {
            return flexibleGridAnchorGeneratorBuilder_.getMessage();
          }
          return object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
       */
      public Builder setFlexibleGridAnchorGenerator(object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator value) {
        if (flexibleGridAnchorGeneratorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          anchorGeneratorOneof_ = value;
          onChanged();
        } else {
          flexibleGridAnchorGeneratorBuilder_.setMessage(value);
        }
        anchorGeneratorOneofCase_ = 4;
        return this;
      }
      /**
       * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
       */
      public Builder setFlexibleGridAnchorGenerator(
          object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.Builder builderForValue) {
        if (flexibleGridAnchorGeneratorBuilder_ == null) {
          anchorGeneratorOneof_ = builderForValue.build();
          onChanged();
        } else {
          flexibleGridAnchorGeneratorBuilder_.setMessage(builderForValue.build());
        }
        anchorGeneratorOneofCase_ = 4;
        return this;
      }
      /**
       * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
       */
      public Builder mergeFlexibleGridAnchorGenerator(object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator value) {
        if (flexibleGridAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 4 &&
              anchorGeneratorOneof_ != object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.getDefaultInstance()) {
            anchorGeneratorOneof_ = object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.newBuilder((object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator) anchorGeneratorOneof_)
                .mergeFrom(value).buildPartial();
          } else {
            anchorGeneratorOneof_ = value;
          }
          onChanged();
        } else {
          if (anchorGeneratorOneofCase_ == 4) {
            flexibleGridAnchorGeneratorBuilder_.mergeFrom(value);
          }
          flexibleGridAnchorGeneratorBuilder_.setMessage(value);
        }
        anchorGeneratorOneofCase_ = 4;
        return this;
      }
      /**
       * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
       */
      public Builder clearFlexibleGridAnchorGenerator() {
        if (flexibleGridAnchorGeneratorBuilder_ == null) {
          if (anchorGeneratorOneofCase_ == 4) {
            anchorGeneratorOneofCase_ = 0;
            anchorGeneratorOneof_ = null;
            onChanged();
          }
        } else {
          if (anchorGeneratorOneofCase_ == 4) {
            anchorGeneratorOneofCase_ = 0;
            anchorGeneratorOneof_ = null;
          }
          flexibleGridAnchorGeneratorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
       */
      public object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.Builder getFlexibleGridAnchorGeneratorBuilder() {
        return getFlexibleGridAnchorGeneratorFieldBuilder().getBuilder();
      }
      /**
       * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
       */
      @java.lang.Override
      public object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGeneratorOrBuilder getFlexibleGridAnchorGeneratorOrBuilder() {
        if ((anchorGeneratorOneofCase_ == 4) && (flexibleGridAnchorGeneratorBuilder_ != null)) {
          return flexibleGridAnchorGeneratorBuilder_.getMessageOrBuilder();
        } else {
          if (anchorGeneratorOneofCase_ == 4) {
            return (object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator) anchorGeneratorOneof_;
          }
          return object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.FlexibleGridAnchorGenerator flexible_grid_anchor_generator = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator, object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.Builder, object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGeneratorOrBuilder>
          getFlexibleGridAnchorGeneratorFieldBuilder() {
        if (flexibleGridAnchorGeneratorBuilder_ == null) {
          if (!(anchorGeneratorOneofCase_ == 4)) {
            anchorGeneratorOneof_ = object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.getDefaultInstance();
          }
          flexibleGridAnchorGeneratorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator, object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator.Builder, object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGeneratorOrBuilder>(
                  (object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.FlexibleGridAnchorGenerator) anchorGeneratorOneof_,
                  getParentForChildren(),
                  isClean());
          anchorGeneratorOneof_ = null;
        }
        anchorGeneratorOneofCase_ = 4;
        onChanged();;
        return flexibleGridAnchorGeneratorBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:object_detection.protos.AnchorGenerator)
    }

    // @@protoc_insertion_point(class_scope:object_detection.protos.AnchorGenerator)
    private static final object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator();
    }

    public static object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AnchorGenerator>
        PARSER = new com.google.protobuf.AbstractParser<AnchorGenerator>() {
      @java.lang.Override
      public AnchorGenerator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnchorGenerator(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnchorGenerator> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnchorGenerator> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public object_detection.protos.AnchorGeneratorOuterClass.AnchorGenerator getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_object_detection_protos_AnchorGenerator_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_object_detection_protos_AnchorGenerator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.object_detection/protos/anchor_generat" +
      "or.proto\022\027object_detection.protos\032<objec" +
      "t_detection/protos/flexible_grid_anchor_" +
      "generator.proto\0323object_detection/protos" +
      "/grid_anchor_generator.proto\0329object_det" +
      "ection/protos/multiscale_anchor_generato" +
      "r.proto\0322object_detection/protos/ssd_anc" +
      "hor_generator.proto\"\202\003\n\017AnchorGenerator\022" +
      "M\n\025grid_anchor_generator\030\001 \001(\0132,.object_" +
      "detection.protos.GridAnchorGeneratorH\000\022K" +
      "\n\024ssd_anchor_generator\030\002 \001(\0132+.object_de" +
      "tection.protos.SsdAnchorGeneratorH\000\022Y\n\033m" +
      "ultiscale_anchor_generator\030\003 \001(\01322.objec" +
      "t_detection.protos.MultiscaleAnchorGener" +
      "atorH\000\022^\n\036flexible_grid_anchor_generator" +
      "\030\004 \001(\01324.object_detection.protos.Flexibl" +
      "eGridAnchorGeneratorH\000B\030\n\026anchor_generat" +
      "or_oneof"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.getDescriptor(),
          object_detection.protos.GridAnchorGeneratorOuterClass.getDescriptor(),
          object_detection.protos.MultiscaleAnchorGeneratorOuterClass.getDescriptor(),
          object_detection.protos.SsdAnchorGeneratorOuterClass.getDescriptor(),
        });
    internal_static_object_detection_protos_AnchorGenerator_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_object_detection_protos_AnchorGenerator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_object_detection_protos_AnchorGenerator_descriptor,
        new java.lang.String[] { "GridAnchorGenerator", "SsdAnchorGenerator", "MultiscaleAnchorGenerator", "FlexibleGridAnchorGenerator", "AnchorGeneratorOneof", });
    object_detection.protos.FlexibleGridAnchorGeneratorOuterClass.getDescriptor();
    object_detection.protos.GridAnchorGeneratorOuterClass.getDescriptor();
    object_detection.protos.MultiscaleAnchorGeneratorOuterClass.getDescriptor();
    object_detection.protos.SsdAnchorGeneratorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
