/*
 * Copyright (c) 2020. Kin-Hong Wong. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/box_coder.proto

package object_detection.protos;

public final class BoxCoderOuterClass {
  private BoxCoderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BoxCoderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:object_detection.protos.BoxCoder)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
     * @return Whether the fasterRcnnBoxCoder field is set.
     */
    boolean hasFasterRcnnBoxCoder();
    /**
     * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
     * @return The fasterRcnnBoxCoder.
     */
    object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder getFasterRcnnBoxCoder();
    /**
     * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
     */
    object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoderOrBuilder getFasterRcnnBoxCoderOrBuilder();

    /**
     * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
     * @return Whether the meanStddevBoxCoder field is set.
     */
    boolean hasMeanStddevBoxCoder();
    /**
     * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
     * @return The meanStddevBoxCoder.
     */
    object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder getMeanStddevBoxCoder();
    /**
     * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
     */
    object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoderOrBuilder getMeanStddevBoxCoderOrBuilder();

    /**
     * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
     * @return Whether the squareBoxCoder field is set.
     */
    boolean hasSquareBoxCoder();
    /**
     * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
     * @return The squareBoxCoder.
     */
    object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder getSquareBoxCoder();
    /**
     * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
     */
    object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoderOrBuilder getSquareBoxCoderOrBuilder();

    /**
     * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
     * @return Whether the keypointBoxCoder field is set.
     */
    boolean hasKeypointBoxCoder();
    /**
     * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
     * @return The keypointBoxCoder.
     */
    object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder getKeypointBoxCoder();
    /**
     * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
     */
    object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoderOrBuilder getKeypointBoxCoderOrBuilder();

    public object_detection.protos.BoxCoderOuterClass.BoxCoder.BoxCoderOneofCase getBoxCoderOneofCase();
  }
  /**
   * <pre>
   * Configuration proto for the box coder to be used in the object detection
   * pipeline. See core/box_coder.py for details.
   * </pre>
   *
   * Protobuf type {@code object_detection.protos.BoxCoder}
   */
  public static final class BoxCoder extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:object_detection.protos.BoxCoder)
      BoxCoderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BoxCoder.newBuilder() to construct.
    private BoxCoder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BoxCoder() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BoxCoder();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BoxCoder(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.Builder subBuilder = null;
              if (boxCoderOneofCase_ == 1) {
                subBuilder = ((object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder) boxCoderOneof_).toBuilder();
              }
              boxCoderOneof_ =
                  input.readMessage(object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder) boxCoderOneof_);
                boxCoderOneof_ = subBuilder.buildPartial();
              }
              boxCoderOneofCase_ = 1;
              break;
            }
            case 18: {
              object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.Builder subBuilder = null;
              if (boxCoderOneofCase_ == 2) {
                subBuilder = ((object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder) boxCoderOneof_).toBuilder();
              }
              boxCoderOneof_ =
                  input.readMessage(object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder) boxCoderOneof_);
                boxCoderOneof_ = subBuilder.buildPartial();
              }
              boxCoderOneofCase_ = 2;
              break;
            }
            case 26: {
              object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.Builder subBuilder = null;
              if (boxCoderOneofCase_ == 3) {
                subBuilder = ((object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) boxCoderOneof_).toBuilder();
              }
              boxCoderOneof_ =
                  input.readMessage(object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) boxCoderOneof_);
                boxCoderOneof_ = subBuilder.buildPartial();
              }
              boxCoderOneofCase_ = 3;
              break;
            }
            case 34: {
              object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.Builder subBuilder = null;
              if (boxCoderOneofCase_ == 4) {
                subBuilder = ((object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder) boxCoderOneof_).toBuilder();
              }
              boxCoderOneof_ =
                  input.readMessage(object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder) boxCoderOneof_);
                boxCoderOneof_ = subBuilder.buildPartial();
              }
              boxCoderOneofCase_ = 4;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return object_detection.protos.BoxCoderOuterClass.internal_static_object_detection_protos_BoxCoder_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return object_detection.protos.BoxCoderOuterClass.internal_static_object_detection_protos_BoxCoder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              object_detection.protos.BoxCoderOuterClass.BoxCoder.class, object_detection.protos.BoxCoderOuterClass.BoxCoder.Builder.class);
    }

    private int bitField0_;
    private int boxCoderOneofCase_ = 0;
    private java.lang.Object boxCoderOneof_;
    public enum BoxCoderOneofCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      FASTER_RCNN_BOX_CODER(1),
      MEAN_STDDEV_BOX_CODER(2),
      SQUARE_BOX_CODER(3),
      KEYPOINT_BOX_CODER(4),
      BOXCODERONEOF_NOT_SET(0);
      private final int value;
      private BoxCoderOneofCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BoxCoderOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static BoxCoderOneofCase forNumber(int value) {
        switch (value) {
          case 1: return FASTER_RCNN_BOX_CODER;
          case 2: return MEAN_STDDEV_BOX_CODER;
          case 3: return SQUARE_BOX_CODER;
          case 4: return KEYPOINT_BOX_CODER;
          case 0: return BOXCODERONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BoxCoderOneofCase
    getBoxCoderOneofCase() {
      return BoxCoderOneofCase.forNumber(
          boxCoderOneofCase_);
    }

    public static final int FASTER_RCNN_BOX_CODER_FIELD_NUMBER = 1;
    /**
     * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
     * @return Whether the fasterRcnnBoxCoder field is set.
     */
    @java.lang.Override
    public boolean hasFasterRcnnBoxCoder() {
      return boxCoderOneofCase_ == 1;
    }
    /**
     * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
     * @return The fasterRcnnBoxCoder.
     */
    @java.lang.Override
    public object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder getFasterRcnnBoxCoder() {
      if (boxCoderOneofCase_ == 1) {
         return (object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder) boxCoderOneof_;
      }
      return object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.getDefaultInstance();
    }
    /**
     * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
     */
    @java.lang.Override
    public object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoderOrBuilder getFasterRcnnBoxCoderOrBuilder() {
      if (boxCoderOneofCase_ == 1) {
         return (object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder) boxCoderOneof_;
      }
      return object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.getDefaultInstance();
    }

    public static final int MEAN_STDDEV_BOX_CODER_FIELD_NUMBER = 2;
    /**
     * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
     * @return Whether the meanStddevBoxCoder field is set.
     */
    @java.lang.Override
    public boolean hasMeanStddevBoxCoder() {
      return boxCoderOneofCase_ == 2;
    }
    /**
     * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
     * @return The meanStddevBoxCoder.
     */
    @java.lang.Override
    public object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder getMeanStddevBoxCoder() {
      if (boxCoderOneofCase_ == 2) {
         return (object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder) boxCoderOneof_;
      }
      return object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.getDefaultInstance();
    }
    /**
     * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
     */
    @java.lang.Override
    public object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoderOrBuilder getMeanStddevBoxCoderOrBuilder() {
      if (boxCoderOneofCase_ == 2) {
         return (object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder) boxCoderOneof_;
      }
      return object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.getDefaultInstance();
    }

    public static final int SQUARE_BOX_CODER_FIELD_NUMBER = 3;
    /**
     * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
     * @return Whether the squareBoxCoder field is set.
     */
    @java.lang.Override
    public boolean hasSquareBoxCoder() {
      return boxCoderOneofCase_ == 3;
    }
    /**
     * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
     * @return The squareBoxCoder.
     */
    @java.lang.Override
    public object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder getSquareBoxCoder() {
      if (boxCoderOneofCase_ == 3) {
         return (object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) boxCoderOneof_;
      }
      return object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.getDefaultInstance();
    }
    /**
     * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
     */
    @java.lang.Override
    public object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoderOrBuilder getSquareBoxCoderOrBuilder() {
      if (boxCoderOneofCase_ == 3) {
         return (object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) boxCoderOneof_;
      }
      return object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.getDefaultInstance();
    }

    public static final int KEYPOINT_BOX_CODER_FIELD_NUMBER = 4;
    /**
     * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
     * @return Whether the keypointBoxCoder field is set.
     */
    @java.lang.Override
    public boolean hasKeypointBoxCoder() {
      return boxCoderOneofCase_ == 4;
    }
    /**
     * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
     * @return The keypointBoxCoder.
     */
    @java.lang.Override
    public object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder getKeypointBoxCoder() {
      if (boxCoderOneofCase_ == 4) {
         return (object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder) boxCoderOneof_;
      }
      return object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.getDefaultInstance();
    }
    /**
     * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
     */
    @java.lang.Override
    public object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoderOrBuilder getKeypointBoxCoderOrBuilder() {
      if (boxCoderOneofCase_ == 4) {
         return (object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder) boxCoderOneof_;
      }
      return object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (boxCoderOneofCase_ == 1) {
        output.writeMessage(1, (object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder) boxCoderOneof_);
      }
      if (boxCoderOneofCase_ == 2) {
        output.writeMessage(2, (object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder) boxCoderOneof_);
      }
      if (boxCoderOneofCase_ == 3) {
        output.writeMessage(3, (object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) boxCoderOneof_);
      }
      if (boxCoderOneofCase_ == 4) {
        output.writeMessage(4, (object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder) boxCoderOneof_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (boxCoderOneofCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder) boxCoderOneof_);
      }
      if (boxCoderOneofCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder) boxCoderOneof_);
      }
      if (boxCoderOneofCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) boxCoderOneof_);
      }
      if (boxCoderOneofCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder) boxCoderOneof_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof object_detection.protos.BoxCoderOuterClass.BoxCoder)) {
        return super.equals(obj);
      }
      object_detection.protos.BoxCoderOuterClass.BoxCoder other = (object_detection.protos.BoxCoderOuterClass.BoxCoder) obj;

      if (!getBoxCoderOneofCase().equals(other.getBoxCoderOneofCase())) return false;
      switch (boxCoderOneofCase_) {
        case 1:
          if (!getFasterRcnnBoxCoder()
              .equals(other.getFasterRcnnBoxCoder())) return false;
          break;
        case 2:
          if (!getMeanStddevBoxCoder()
              .equals(other.getMeanStddevBoxCoder())) return false;
          break;
        case 3:
          if (!getSquareBoxCoder()
              .equals(other.getSquareBoxCoder())) return false;
          break;
        case 4:
          if (!getKeypointBoxCoder()
              .equals(other.getKeypointBoxCoder())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (boxCoderOneofCase_) {
        case 1:
          hash = (37 * hash) + FASTER_RCNN_BOX_CODER_FIELD_NUMBER;
          hash = (53 * hash) + getFasterRcnnBoxCoder().hashCode();
          break;
        case 2:
          hash = (37 * hash) + MEAN_STDDEV_BOX_CODER_FIELD_NUMBER;
          hash = (53 * hash) + getMeanStddevBoxCoder().hashCode();
          break;
        case 3:
          hash = (37 * hash) + SQUARE_BOX_CODER_FIELD_NUMBER;
          hash = (53 * hash) + getSquareBoxCoder().hashCode();
          break;
        case 4:
          hash = (37 * hash) + KEYPOINT_BOX_CODER_FIELD_NUMBER;
          hash = (53 * hash) + getKeypointBoxCoder().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.BoxCoderOuterClass.BoxCoder parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(object_detection.protos.BoxCoderOuterClass.BoxCoder prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration proto for the box coder to be used in the object detection
     * pipeline. See core/box_coder.py for details.
     * </pre>
     *
     * Protobuf type {@code object_detection.protos.BoxCoder}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:object_detection.protos.BoxCoder)
        object_detection.protos.BoxCoderOuterClass.BoxCoderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return object_detection.protos.BoxCoderOuterClass.internal_static_object_detection_protos_BoxCoder_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return object_detection.protos.BoxCoderOuterClass.internal_static_object_detection_protos_BoxCoder_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                object_detection.protos.BoxCoderOuterClass.BoxCoder.class, object_detection.protos.BoxCoderOuterClass.BoxCoder.Builder.class);
      }

      // Construct using object_detection.protos.BoxCoderOuterClass.BoxCoder.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        boxCoderOneofCase_ = 0;
        boxCoderOneof_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return object_detection.protos.BoxCoderOuterClass.internal_static_object_detection_protos_BoxCoder_descriptor;
      }

      @java.lang.Override
      public object_detection.protos.BoxCoderOuterClass.BoxCoder getDefaultInstanceForType() {
        return object_detection.protos.BoxCoderOuterClass.BoxCoder.getDefaultInstance();
      }

      @java.lang.Override
      public object_detection.protos.BoxCoderOuterClass.BoxCoder build() {
        object_detection.protos.BoxCoderOuterClass.BoxCoder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public object_detection.protos.BoxCoderOuterClass.BoxCoder buildPartial() {
        object_detection.protos.BoxCoderOuterClass.BoxCoder result = new object_detection.protos.BoxCoderOuterClass.BoxCoder(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (boxCoderOneofCase_ == 1) {
          if (fasterRcnnBoxCoderBuilder_ == null) {
            result.boxCoderOneof_ = boxCoderOneof_;
          } else {
            result.boxCoderOneof_ = fasterRcnnBoxCoderBuilder_.build();
          }
        }
        if (boxCoderOneofCase_ == 2) {
          if (meanStddevBoxCoderBuilder_ == null) {
            result.boxCoderOneof_ = boxCoderOneof_;
          } else {
            result.boxCoderOneof_ = meanStddevBoxCoderBuilder_.build();
          }
        }
        if (boxCoderOneofCase_ == 3) {
          if (squareBoxCoderBuilder_ == null) {
            result.boxCoderOneof_ = boxCoderOneof_;
          } else {
            result.boxCoderOneof_ = squareBoxCoderBuilder_.build();
          }
        }
        if (boxCoderOneofCase_ == 4) {
          if (keypointBoxCoderBuilder_ == null) {
            result.boxCoderOneof_ = boxCoderOneof_;
          } else {
            result.boxCoderOneof_ = keypointBoxCoderBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.boxCoderOneofCase_ = boxCoderOneofCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof object_detection.protos.BoxCoderOuterClass.BoxCoder) {
          return mergeFrom((object_detection.protos.BoxCoderOuterClass.BoxCoder)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(object_detection.protos.BoxCoderOuterClass.BoxCoder other) {
        if (other == object_detection.protos.BoxCoderOuterClass.BoxCoder.getDefaultInstance()) return this;
        switch (other.getBoxCoderOneofCase()) {
          case FASTER_RCNN_BOX_CODER: {
            mergeFasterRcnnBoxCoder(other.getFasterRcnnBoxCoder());
            break;
          }
          case MEAN_STDDEV_BOX_CODER: {
            mergeMeanStddevBoxCoder(other.getMeanStddevBoxCoder());
            break;
          }
          case SQUARE_BOX_CODER: {
            mergeSquareBoxCoder(other.getSquareBoxCoder());
            break;
          }
          case KEYPOINT_BOX_CODER: {
            mergeKeypointBoxCoder(other.getKeypointBoxCoder());
            break;
          }
          case BOXCODERONEOF_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        object_detection.protos.BoxCoderOuterClass.BoxCoder parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (object_detection.protos.BoxCoderOuterClass.BoxCoder) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int boxCoderOneofCase_ = 0;
      private java.lang.Object boxCoderOneof_;
      public BoxCoderOneofCase
          getBoxCoderOneofCase() {
        return BoxCoderOneofCase.forNumber(
            boxCoderOneofCase_);
      }

      public Builder clearBoxCoderOneof() {
        boxCoderOneofCase_ = 0;
        boxCoderOneof_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder, object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.Builder, object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoderOrBuilder> fasterRcnnBoxCoderBuilder_;
      /**
       * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
       * @return Whether the fasterRcnnBoxCoder field is set.
       */
      @java.lang.Override
      public boolean hasFasterRcnnBoxCoder() {
        return boxCoderOneofCase_ == 1;
      }
      /**
       * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
       * @return The fasterRcnnBoxCoder.
       */
      @java.lang.Override
      public object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder getFasterRcnnBoxCoder() {
        if (fasterRcnnBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 1) {
            return (object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder) boxCoderOneof_;
          }
          return object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.getDefaultInstance();
        } else {
          if (boxCoderOneofCase_ == 1) {
            return fasterRcnnBoxCoderBuilder_.getMessage();
          }
          return object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
       */
      public Builder setFasterRcnnBoxCoder(object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder value) {
        if (fasterRcnnBoxCoderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          boxCoderOneof_ = value;
          onChanged();
        } else {
          fasterRcnnBoxCoderBuilder_.setMessage(value);
        }
        boxCoderOneofCase_ = 1;
        return this;
      }
      /**
       * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
       */
      public Builder setFasterRcnnBoxCoder(
          object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.Builder builderForValue) {
        if (fasterRcnnBoxCoderBuilder_ == null) {
          boxCoderOneof_ = builderForValue.build();
          onChanged();
        } else {
          fasterRcnnBoxCoderBuilder_.setMessage(builderForValue.build());
        }
        boxCoderOneofCase_ = 1;
        return this;
      }
      /**
       * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
       */
      public Builder mergeFasterRcnnBoxCoder(object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder value) {
        if (fasterRcnnBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 1 &&
              boxCoderOneof_ != object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.getDefaultInstance()) {
            boxCoderOneof_ = object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.newBuilder((object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder) boxCoderOneof_)
                .mergeFrom(value).buildPartial();
          } else {
            boxCoderOneof_ = value;
          }
          onChanged();
        } else {
          if (boxCoderOneofCase_ == 1) {
            fasterRcnnBoxCoderBuilder_.mergeFrom(value);
          }
          fasterRcnnBoxCoderBuilder_.setMessage(value);
        }
        boxCoderOneofCase_ = 1;
        return this;
      }
      /**
       * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
       */
      public Builder clearFasterRcnnBoxCoder() {
        if (fasterRcnnBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 1) {
            boxCoderOneofCase_ = 0;
            boxCoderOneof_ = null;
            onChanged();
          }
        } else {
          if (boxCoderOneofCase_ == 1) {
            boxCoderOneofCase_ = 0;
            boxCoderOneof_ = null;
          }
          fasterRcnnBoxCoderBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
       */
      public object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.Builder getFasterRcnnBoxCoderBuilder() {
        return getFasterRcnnBoxCoderFieldBuilder().getBuilder();
      }
      /**
       * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
       */
      @java.lang.Override
      public object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoderOrBuilder getFasterRcnnBoxCoderOrBuilder() {
        if ((boxCoderOneofCase_ == 1) && (fasterRcnnBoxCoderBuilder_ != null)) {
          return fasterRcnnBoxCoderBuilder_.getMessageOrBuilder();
        } else {
          if (boxCoderOneofCase_ == 1) {
            return (object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder) boxCoderOneof_;
          }
          return object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.FasterRcnnBoxCoder faster_rcnn_box_coder = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder, object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.Builder, object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoderOrBuilder>
          getFasterRcnnBoxCoderFieldBuilder() {
        if (fasterRcnnBoxCoderBuilder_ == null) {
          if (!(boxCoderOneofCase_ == 1)) {
            boxCoderOneof_ = object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.getDefaultInstance();
          }
          fasterRcnnBoxCoderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder, object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder.Builder, object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoderOrBuilder>(
                  (object_detection.protos.FasterRcnnBoxCoderOuterClass.FasterRcnnBoxCoder) boxCoderOneof_,
                  getParentForChildren(),
                  isClean());
          boxCoderOneof_ = null;
        }
        boxCoderOneofCase_ = 1;
        onChanged();;
        return fasterRcnnBoxCoderBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder, object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.Builder, object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoderOrBuilder> meanStddevBoxCoderBuilder_;
      /**
       * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
       * @return Whether the meanStddevBoxCoder field is set.
       */
      @java.lang.Override
      public boolean hasMeanStddevBoxCoder() {
        return boxCoderOneofCase_ == 2;
      }
      /**
       * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
       * @return The meanStddevBoxCoder.
       */
      @java.lang.Override
      public object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder getMeanStddevBoxCoder() {
        if (meanStddevBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 2) {
            return (object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder) boxCoderOneof_;
          }
          return object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.getDefaultInstance();
        } else {
          if (boxCoderOneofCase_ == 2) {
            return meanStddevBoxCoderBuilder_.getMessage();
          }
          return object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
       */
      public Builder setMeanStddevBoxCoder(object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder value) {
        if (meanStddevBoxCoderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          boxCoderOneof_ = value;
          onChanged();
        } else {
          meanStddevBoxCoderBuilder_.setMessage(value);
        }
        boxCoderOneofCase_ = 2;
        return this;
      }
      /**
       * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
       */
      public Builder setMeanStddevBoxCoder(
          object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.Builder builderForValue) {
        if (meanStddevBoxCoderBuilder_ == null) {
          boxCoderOneof_ = builderForValue.build();
          onChanged();
        } else {
          meanStddevBoxCoderBuilder_.setMessage(builderForValue.build());
        }
        boxCoderOneofCase_ = 2;
        return this;
      }
      /**
       * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
       */
      public Builder mergeMeanStddevBoxCoder(object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder value) {
        if (meanStddevBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 2 &&
              boxCoderOneof_ != object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.getDefaultInstance()) {
            boxCoderOneof_ = object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.newBuilder((object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder) boxCoderOneof_)
                .mergeFrom(value).buildPartial();
          } else {
            boxCoderOneof_ = value;
          }
          onChanged();
        } else {
          if (boxCoderOneofCase_ == 2) {
            meanStddevBoxCoderBuilder_.mergeFrom(value);
          }
          meanStddevBoxCoderBuilder_.setMessage(value);
        }
        boxCoderOneofCase_ = 2;
        return this;
      }
      /**
       * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
       */
      public Builder clearMeanStddevBoxCoder() {
        if (meanStddevBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 2) {
            boxCoderOneofCase_ = 0;
            boxCoderOneof_ = null;
            onChanged();
          }
        } else {
          if (boxCoderOneofCase_ == 2) {
            boxCoderOneofCase_ = 0;
            boxCoderOneof_ = null;
          }
          meanStddevBoxCoderBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
       */
      public object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.Builder getMeanStddevBoxCoderBuilder() {
        return getMeanStddevBoxCoderFieldBuilder().getBuilder();
      }
      /**
       * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
       */
      @java.lang.Override
      public object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoderOrBuilder getMeanStddevBoxCoderOrBuilder() {
        if ((boxCoderOneofCase_ == 2) && (meanStddevBoxCoderBuilder_ != null)) {
          return meanStddevBoxCoderBuilder_.getMessageOrBuilder();
        } else {
          if (boxCoderOneofCase_ == 2) {
            return (object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder) boxCoderOneof_;
          }
          return object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.MeanStddevBoxCoder mean_stddev_box_coder = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder, object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.Builder, object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoderOrBuilder>
          getMeanStddevBoxCoderFieldBuilder() {
        if (meanStddevBoxCoderBuilder_ == null) {
          if (!(boxCoderOneofCase_ == 2)) {
            boxCoderOneof_ = object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.getDefaultInstance();
          }
          meanStddevBoxCoderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder, object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder.Builder, object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoderOrBuilder>(
                  (object_detection.protos.MeanStddevBoxCoderOuterClass.MeanStddevBoxCoder) boxCoderOneof_,
                  getParentForChildren(),
                  isClean());
          boxCoderOneof_ = null;
        }
        boxCoderOneofCase_ = 2;
        onChanged();;
        return meanStddevBoxCoderBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder, object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.Builder, object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoderOrBuilder> squareBoxCoderBuilder_;
      /**
       * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
       * @return Whether the squareBoxCoder field is set.
       */
      @java.lang.Override
      public boolean hasSquareBoxCoder() {
        return boxCoderOneofCase_ == 3;
      }
      /**
       * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
       * @return The squareBoxCoder.
       */
      @java.lang.Override
      public object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder getSquareBoxCoder() {
        if (squareBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 3) {
            return (object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) boxCoderOneof_;
          }
          return object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.getDefaultInstance();
        } else {
          if (boxCoderOneofCase_ == 3) {
            return squareBoxCoderBuilder_.getMessage();
          }
          return object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
       */
      public Builder setSquareBoxCoder(object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder value) {
        if (squareBoxCoderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          boxCoderOneof_ = value;
          onChanged();
        } else {
          squareBoxCoderBuilder_.setMessage(value);
        }
        boxCoderOneofCase_ = 3;
        return this;
      }
      /**
       * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
       */
      public Builder setSquareBoxCoder(
          object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.Builder builderForValue) {
        if (squareBoxCoderBuilder_ == null) {
          boxCoderOneof_ = builderForValue.build();
          onChanged();
        } else {
          squareBoxCoderBuilder_.setMessage(builderForValue.build());
        }
        boxCoderOneofCase_ = 3;
        return this;
      }
      /**
       * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
       */
      public Builder mergeSquareBoxCoder(object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder value) {
        if (squareBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 3 &&
              boxCoderOneof_ != object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.getDefaultInstance()) {
            boxCoderOneof_ = object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.newBuilder((object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) boxCoderOneof_)
                .mergeFrom(value).buildPartial();
          } else {
            boxCoderOneof_ = value;
          }
          onChanged();
        } else {
          if (boxCoderOneofCase_ == 3) {
            squareBoxCoderBuilder_.mergeFrom(value);
          }
          squareBoxCoderBuilder_.setMessage(value);
        }
        boxCoderOneofCase_ = 3;
        return this;
      }
      /**
       * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
       */
      public Builder clearSquareBoxCoder() {
        if (squareBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 3) {
            boxCoderOneofCase_ = 0;
            boxCoderOneof_ = null;
            onChanged();
          }
        } else {
          if (boxCoderOneofCase_ == 3) {
            boxCoderOneofCase_ = 0;
            boxCoderOneof_ = null;
          }
          squareBoxCoderBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
       */
      public object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.Builder getSquareBoxCoderBuilder() {
        return getSquareBoxCoderFieldBuilder().getBuilder();
      }
      /**
       * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
       */
      @java.lang.Override
      public object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoderOrBuilder getSquareBoxCoderOrBuilder() {
        if ((boxCoderOneofCase_ == 3) && (squareBoxCoderBuilder_ != null)) {
          return squareBoxCoderBuilder_.getMessageOrBuilder();
        } else {
          if (boxCoderOneofCase_ == 3) {
            return (object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) boxCoderOneof_;
          }
          return object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.SquareBoxCoder square_box_coder = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder, object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.Builder, object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoderOrBuilder>
          getSquareBoxCoderFieldBuilder() {
        if (squareBoxCoderBuilder_ == null) {
          if (!(boxCoderOneofCase_ == 3)) {
            boxCoderOneof_ = object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.getDefaultInstance();
          }
          squareBoxCoderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder, object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.Builder, object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoderOrBuilder>(
                  (object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) boxCoderOneof_,
                  getParentForChildren(),
                  isClean());
          boxCoderOneof_ = null;
        }
        boxCoderOneofCase_ = 3;
        onChanged();;
        return squareBoxCoderBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder, object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.Builder, object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoderOrBuilder> keypointBoxCoderBuilder_;
      /**
       * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
       * @return Whether the keypointBoxCoder field is set.
       */
      @java.lang.Override
      public boolean hasKeypointBoxCoder() {
        return boxCoderOneofCase_ == 4;
      }
      /**
       * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
       * @return The keypointBoxCoder.
       */
      @java.lang.Override
      public object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder getKeypointBoxCoder() {
        if (keypointBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 4) {
            return (object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder) boxCoderOneof_;
          }
          return object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.getDefaultInstance();
        } else {
          if (boxCoderOneofCase_ == 4) {
            return keypointBoxCoderBuilder_.getMessage();
          }
          return object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
       */
      public Builder setKeypointBoxCoder(object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder value) {
        if (keypointBoxCoderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          boxCoderOneof_ = value;
          onChanged();
        } else {
          keypointBoxCoderBuilder_.setMessage(value);
        }
        boxCoderOneofCase_ = 4;
        return this;
      }
      /**
       * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
       */
      public Builder setKeypointBoxCoder(
          object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.Builder builderForValue) {
        if (keypointBoxCoderBuilder_ == null) {
          boxCoderOneof_ = builderForValue.build();
          onChanged();
        } else {
          keypointBoxCoderBuilder_.setMessage(builderForValue.build());
        }
        boxCoderOneofCase_ = 4;
        return this;
      }
      /**
       * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
       */
      public Builder mergeKeypointBoxCoder(object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder value) {
        if (keypointBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 4 &&
              boxCoderOneof_ != object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.getDefaultInstance()) {
            boxCoderOneof_ = object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.newBuilder((object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder) boxCoderOneof_)
                .mergeFrom(value).buildPartial();
          } else {
            boxCoderOneof_ = value;
          }
          onChanged();
        } else {
          if (boxCoderOneofCase_ == 4) {
            keypointBoxCoderBuilder_.mergeFrom(value);
          }
          keypointBoxCoderBuilder_.setMessage(value);
        }
        boxCoderOneofCase_ = 4;
        return this;
      }
      /**
       * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
       */
      public Builder clearKeypointBoxCoder() {
        if (keypointBoxCoderBuilder_ == null) {
          if (boxCoderOneofCase_ == 4) {
            boxCoderOneofCase_ = 0;
            boxCoderOneof_ = null;
            onChanged();
          }
        } else {
          if (boxCoderOneofCase_ == 4) {
            boxCoderOneofCase_ = 0;
            boxCoderOneof_ = null;
          }
          keypointBoxCoderBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
       */
      public object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.Builder getKeypointBoxCoderBuilder() {
        return getKeypointBoxCoderFieldBuilder().getBuilder();
      }
      /**
       * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
       */
      @java.lang.Override
      public object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoderOrBuilder getKeypointBoxCoderOrBuilder() {
        if ((boxCoderOneofCase_ == 4) && (keypointBoxCoderBuilder_ != null)) {
          return keypointBoxCoderBuilder_.getMessageOrBuilder();
        } else {
          if (boxCoderOneofCase_ == 4) {
            return (object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder) boxCoderOneof_;
          }
          return object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.getDefaultInstance();
        }
      }
      /**
       * <code>.object_detection.protos.KeypointBoxCoder keypoint_box_coder = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder, object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.Builder, object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoderOrBuilder>
          getKeypointBoxCoderFieldBuilder() {
        if (keypointBoxCoderBuilder_ == null) {
          if (!(boxCoderOneofCase_ == 4)) {
            boxCoderOneof_ = object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.getDefaultInstance();
          }
          keypointBoxCoderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder, object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder.Builder, object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoderOrBuilder>(
                  (object_detection.protos.KeypointBoxCoderOuterClass.KeypointBoxCoder) boxCoderOneof_,
                  getParentForChildren(),
                  isClean());
          boxCoderOneof_ = null;
        }
        boxCoderOneofCase_ = 4;
        onChanged();;
        return keypointBoxCoderBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:object_detection.protos.BoxCoder)
    }

    // @@protoc_insertion_point(class_scope:object_detection.protos.BoxCoder)
    private static final object_detection.protos.BoxCoderOuterClass.BoxCoder DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new object_detection.protos.BoxCoderOuterClass.BoxCoder();
    }

    public static object_detection.protos.BoxCoderOuterClass.BoxCoder getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BoxCoder>
        PARSER = new com.google.protobuf.AbstractParser<BoxCoder>() {
      @java.lang.Override
      public BoxCoder parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoxCoder(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoxCoder> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BoxCoder> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public object_detection.protos.BoxCoderOuterClass.BoxCoder getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_object_detection_protos_BoxCoder_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_object_detection_protos_BoxCoder_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'object_detection/protos/box_coder.prot" +
      "o\022\027object_detection.protos\0323object_detec" +
      "tion/protos/faster_rcnn_box_coder.proto\032" +
      "0object_detection/protos/keypoint_box_co" +
      "der.proto\0323object_detection/protos/mean_" +
      "stddev_box_coder.proto\032.object_detection" +
      "/protos/square_box_coder.proto\"\307\002\n\010BoxCo" +
      "der\022L\n\025faster_rcnn_box_coder\030\001 \001(\0132+.obj" +
      "ect_detection.protos.FasterRcnnBoxCoderH" +
      "\000\022L\n\025mean_stddev_box_coder\030\002 \001(\0132+.objec" +
      "t_detection.protos.MeanStddevBoxCoderH\000\022" +
      "C\n\020square_box_coder\030\003 \001(\0132\'.object_detec" +
      "tion.protos.SquareBoxCoderH\000\022G\n\022keypoint" +
      "_box_coder\030\004 \001(\0132).object_detection.prot" +
      "os.KeypointBoxCoderH\000B\021\n\017box_coder_oneof"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          object_detection.protos.FasterRcnnBoxCoderOuterClass.getDescriptor(),
          object_detection.protos.KeypointBoxCoderOuterClass.getDescriptor(),
          object_detection.protos.MeanStddevBoxCoderOuterClass.getDescriptor(),
          object_detection.protos.SquareBoxCoderOuterClass.getDescriptor(),
        });
    internal_static_object_detection_protos_BoxCoder_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_object_detection_protos_BoxCoder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_object_detection_protos_BoxCoder_descriptor,
        new java.lang.String[] { "FasterRcnnBoxCoder", "MeanStddevBoxCoder", "SquareBoxCoder", "KeypointBoxCoder", "BoxCoderOneof", });
    object_detection.protos.FasterRcnnBoxCoderOuterClass.getDescriptor();
    object_detection.protos.KeypointBoxCoderOuterClass.getDescriptor();
    object_detection.protos.MeanStddevBoxCoderOuterClass.getDescriptor();
    object_detection.protos.SquareBoxCoderOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
