/*
 * Copyright (c) 2020. Kin-Hong Wong. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/fpn.proto

package object_detection.protos;

public final class Fpn {
  private Fpn() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FeaturePyramidNetworksOrBuilder extends
      // @@protoc_insertion_point(interface_extends:object_detection.protos.FeaturePyramidNetworks)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * minimum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     * @return Whether the minLevel field is set.
     */
    boolean hasMinLevel();
    /**
     * <pre>
     * minimum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     * @return The minLevel.
     */
    int getMinLevel();

    /**
     * <pre>
     * maximum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     * @return Whether the maxLevel field is set.
     */
    boolean hasMaxLevel();
    /**
     * <pre>
     * maximum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     * @return The maxLevel.
     */
    int getMaxLevel();

    /**
     * <pre>
     * channel depth for additional coarse feature layers.
     * </pre>
     *
     * <code>optional int32 additional_layer_depth = 3 [default = 256];</code>
     * @return Whether the additionalLayerDepth field is set.
     */
    boolean hasAdditionalLayerDepth();
    /**
     * <pre>
     * channel depth for additional coarse feature layers.
     * </pre>
     *
     * <code>optional int32 additional_layer_depth = 3 [default = 256];</code>
     * @return The additionalLayerDepth.
     */
    int getAdditionalLayerDepth();
  }
  /**
   * <pre>
   * Configuration for Feature Pyramid Networks.
   * </pre>
   *
   * Protobuf type {@code object_detection.protos.FeaturePyramidNetworks}
   */
  public static final class FeaturePyramidNetworks extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:object_detection.protos.FeaturePyramidNetworks)
      FeaturePyramidNetworksOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FeaturePyramidNetworks.newBuilder() to construct.
    private FeaturePyramidNetworks(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeaturePyramidNetworks() {
      minLevel_ = 3;
      maxLevel_ = 7;
      additionalLayerDepth_ = 256;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FeaturePyramidNetworks();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FeaturePyramidNetworks(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              minLevel_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              maxLevel_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              additionalLayerDepth_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return object_detection.protos.Fpn.internal_static_object_detection_protos_FeaturePyramidNetworks_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return object_detection.protos.Fpn.internal_static_object_detection_protos_FeaturePyramidNetworks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              object_detection.protos.Fpn.FeaturePyramidNetworks.class, object_detection.protos.Fpn.FeaturePyramidNetworks.Builder.class);
    }

    private int bitField0_;
    public static final int MIN_LEVEL_FIELD_NUMBER = 1;
    private int minLevel_;
    /**
     * <pre>
     * minimum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     * @return Whether the minLevel field is set.
     */
    @java.lang.Override
    public boolean hasMinLevel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * minimum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     * @return The minLevel.
     */
    @java.lang.Override
    public int getMinLevel() {
      return minLevel_;
    }

    public static final int MAX_LEVEL_FIELD_NUMBER = 2;
    private int maxLevel_;
    /**
     * <pre>
     * maximum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     * @return Whether the maxLevel field is set.
     */
    @java.lang.Override
    public boolean hasMaxLevel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * maximum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     * @return The maxLevel.
     */
    @java.lang.Override
    public int getMaxLevel() {
      return maxLevel_;
    }

    public static final int ADDITIONAL_LAYER_DEPTH_FIELD_NUMBER = 3;
    private int additionalLayerDepth_;
    /**
     * <pre>
     * channel depth for additional coarse feature layers.
     * </pre>
     *
     * <code>optional int32 additional_layer_depth = 3 [default = 256];</code>
     * @return Whether the additionalLayerDepth field is set.
     */
    @java.lang.Override
    public boolean hasAdditionalLayerDepth() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * channel depth for additional coarse feature layers.
     * </pre>
     *
     * <code>optional int32 additional_layer_depth = 3 [default = 256];</code>
     * @return The additionalLayerDepth.
     */
    @java.lang.Override
    public int getAdditionalLayerDepth() {
      return additionalLayerDepth_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, minLevel_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, maxLevel_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, additionalLayerDepth_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, minLevel_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxLevel_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, additionalLayerDepth_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof object_detection.protos.Fpn.FeaturePyramidNetworks)) {
        return super.equals(obj);
      }
      object_detection.protos.Fpn.FeaturePyramidNetworks other = (object_detection.protos.Fpn.FeaturePyramidNetworks) obj;

      if (hasMinLevel() != other.hasMinLevel()) return false;
      if (hasMinLevel()) {
        if (getMinLevel()
            != other.getMinLevel()) return false;
      }
      if (hasMaxLevel() != other.hasMaxLevel()) return false;
      if (hasMaxLevel()) {
        if (getMaxLevel()
            != other.getMaxLevel()) return false;
      }
      if (hasAdditionalLayerDepth() != other.hasAdditionalLayerDepth()) return false;
      if (hasAdditionalLayerDepth()) {
        if (getAdditionalLayerDepth()
            != other.getAdditionalLayerDepth()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMinLevel()) {
        hash = (37 * hash) + MIN_LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getMinLevel();
      }
      if (hasMaxLevel()) {
        hash = (37 * hash) + MAX_LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getMaxLevel();
      }
      if (hasAdditionalLayerDepth()) {
        hash = (37 * hash) + ADDITIONAL_LAYER_DEPTH_FIELD_NUMBER;
        hash = (53 * hash) + getAdditionalLayerDepth();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.Fpn.FeaturePyramidNetworks parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(object_detection.protos.Fpn.FeaturePyramidNetworks prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration for Feature Pyramid Networks.
     * </pre>
     *
     * Protobuf type {@code object_detection.protos.FeaturePyramidNetworks}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:object_detection.protos.FeaturePyramidNetworks)
        object_detection.protos.Fpn.FeaturePyramidNetworksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return object_detection.protos.Fpn.internal_static_object_detection_protos_FeaturePyramidNetworks_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return object_detection.protos.Fpn.internal_static_object_detection_protos_FeaturePyramidNetworks_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                object_detection.protos.Fpn.FeaturePyramidNetworks.class, object_detection.protos.Fpn.FeaturePyramidNetworks.Builder.class);
      }

      // Construct using object_detection.protos.Fpn.FeaturePyramidNetworks.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        minLevel_ = 3;
        bitField0_ = (bitField0_ & ~0x00000001);
        maxLevel_ = 7;
        bitField0_ = (bitField0_ & ~0x00000002);
        additionalLayerDepth_ = 256;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return object_detection.protos.Fpn.internal_static_object_detection_protos_FeaturePyramidNetworks_descriptor;
      }

      @java.lang.Override
      public object_detection.protos.Fpn.FeaturePyramidNetworks getDefaultInstanceForType() {
        return object_detection.protos.Fpn.FeaturePyramidNetworks.getDefaultInstance();
      }

      @java.lang.Override
      public object_detection.protos.Fpn.FeaturePyramidNetworks build() {
        object_detection.protos.Fpn.FeaturePyramidNetworks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public object_detection.protos.Fpn.FeaturePyramidNetworks buildPartial() {
        object_detection.protos.Fpn.FeaturePyramidNetworks result = new object_detection.protos.Fpn.FeaturePyramidNetworks(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.minLevel_ = minLevel_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.maxLevel_ = maxLevel_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.additionalLayerDepth_ = additionalLayerDepth_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof object_detection.protos.Fpn.FeaturePyramidNetworks) {
          return mergeFrom((object_detection.protos.Fpn.FeaturePyramidNetworks)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(object_detection.protos.Fpn.FeaturePyramidNetworks other) {
        if (other == object_detection.protos.Fpn.FeaturePyramidNetworks.getDefaultInstance()) return this;
        if (other.hasMinLevel()) {
          setMinLevel(other.getMinLevel());
        }
        if (other.hasMaxLevel()) {
          setMaxLevel(other.getMaxLevel());
        }
        if (other.hasAdditionalLayerDepth()) {
          setAdditionalLayerDepth(other.getAdditionalLayerDepth());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        object_detection.protos.Fpn.FeaturePyramidNetworks parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (object_detection.protos.Fpn.FeaturePyramidNetworks) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int minLevel_ = 3;
      /**
       * <pre>
       * minimum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       * @return Whether the minLevel field is set.
       */
      @java.lang.Override
      public boolean hasMinLevel() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * minimum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       * @return The minLevel.
       */
      @java.lang.Override
      public int getMinLevel() {
        return minLevel_;
      }
      /**
       * <pre>
       * minimum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       * @param value The minLevel to set.
       * @return This builder for chaining.
       */
      public Builder setMinLevel(int value) {
        bitField0_ |= 0x00000001;
        minLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * minimum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        minLevel_ = 3;
        onChanged();
        return this;
      }

      private int maxLevel_ = 7;
      /**
       * <pre>
       * maximum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       * @return Whether the maxLevel field is set.
       */
      @java.lang.Override
      public boolean hasMaxLevel() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * maximum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       * @return The maxLevel.
       */
      @java.lang.Override
      public int getMaxLevel() {
        return maxLevel_;
      }
      /**
       * <pre>
       * maximum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       * @param value The maxLevel to set.
       * @return This builder for chaining.
       */
      public Builder setMaxLevel(int value) {
        bitField0_ |= 0x00000002;
        maxLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * maximum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxLevel_ = 7;
        onChanged();
        return this;
      }

      private int additionalLayerDepth_ = 256;
      /**
       * <pre>
       * channel depth for additional coarse feature layers.
       * </pre>
       *
       * <code>optional int32 additional_layer_depth = 3 [default = 256];</code>
       * @return Whether the additionalLayerDepth field is set.
       */
      @java.lang.Override
      public boolean hasAdditionalLayerDepth() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * channel depth for additional coarse feature layers.
       * </pre>
       *
       * <code>optional int32 additional_layer_depth = 3 [default = 256];</code>
       * @return The additionalLayerDepth.
       */
      @java.lang.Override
      public int getAdditionalLayerDepth() {
        return additionalLayerDepth_;
      }
      /**
       * <pre>
       * channel depth for additional coarse feature layers.
       * </pre>
       *
       * <code>optional int32 additional_layer_depth = 3 [default = 256];</code>
       * @param value The additionalLayerDepth to set.
       * @return This builder for chaining.
       */
      public Builder setAdditionalLayerDepth(int value) {
        bitField0_ |= 0x00000004;
        additionalLayerDepth_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * channel depth for additional coarse feature layers.
       * </pre>
       *
       * <code>optional int32 additional_layer_depth = 3 [default = 256];</code>
       * @return This builder for chaining.
       */
      public Builder clearAdditionalLayerDepth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        additionalLayerDepth_ = 256;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:object_detection.protos.FeaturePyramidNetworks)
    }

    // @@protoc_insertion_point(class_scope:object_detection.protos.FeaturePyramidNetworks)
    private static final object_detection.protos.Fpn.FeaturePyramidNetworks DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new object_detection.protos.Fpn.FeaturePyramidNetworks();
    }

    public static object_detection.protos.Fpn.FeaturePyramidNetworks getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FeaturePyramidNetworks>
        PARSER = new com.google.protobuf.AbstractParser<FeaturePyramidNetworks>() {
      @java.lang.Override
      public FeaturePyramidNetworks parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeaturePyramidNetworks(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FeaturePyramidNetworks> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeaturePyramidNetworks> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public object_detection.protos.Fpn.FeaturePyramidNetworks getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BidirectionalFeaturePyramidNetworksOrBuilder extends
      // @@protoc_insertion_point(interface_extends:object_detection.protos.BidirectionalFeaturePyramidNetworks)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * minimum level in the feature pyramid.
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     * @return Whether the minLevel field is set.
     */
    boolean hasMinLevel();
    /**
     * <pre>
     * minimum level in the feature pyramid.
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     * @return The minLevel.
     */
    int getMinLevel();

    /**
     * <pre>
     * maximum level in the feature pyramid.
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     * @return Whether the maxLevel field is set.
     */
    boolean hasMaxLevel();
    /**
     * <pre>
     * maximum level in the feature pyramid.
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     * @return The maxLevel.
     */
    int getMaxLevel();

    /**
     * <pre>
     * The number of repeated top-down bottom-up iterations for BiFPN-based
     * feature extractors (bidirectional feature pyramid networks).
     * </pre>
     *
     * <code>optional int32 num_iterations = 3;</code>
     * @return Whether the numIterations field is set.
     */
    boolean hasNumIterations();
    /**
     * <pre>
     * The number of repeated top-down bottom-up iterations for BiFPN-based
     * feature extractors (bidirectional feature pyramid networks).
     * </pre>
     *
     * <code>optional int32 num_iterations = 3;</code>
     * @return The numIterations.
     */
    int getNumIterations();

    /**
     * <pre>
     * The number of filters (channels) to use in feature pyramid layers for
     * BiFPN-based feature extractors (bidirectional feature pyramid networks).
     * </pre>
     *
     * <code>optional int32 num_filters = 4;</code>
     * @return Whether the numFilters field is set.
     */
    boolean hasNumFilters();
    /**
     * <pre>
     * The number of filters (channels) to use in feature pyramid layers for
     * BiFPN-based feature extractors (bidirectional feature pyramid networks).
     * </pre>
     *
     * <code>optional int32 num_filters = 4;</code>
     * @return The numFilters.
     */
    int getNumFilters();

    /**
     * <pre>
     * Method used to combine inputs to BiFPN nodes.
     * </pre>
     *
     * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
     * @return Whether the combineMethod field is set.
     */
    boolean hasCombineMethod();
    /**
     * <pre>
     * Method used to combine inputs to BiFPN nodes.
     * </pre>
     *
     * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
     * @return The combineMethod.
     */
    java.lang.String getCombineMethod();
    /**
     * <pre>
     * Method used to combine inputs to BiFPN nodes.
     * </pre>
     *
     * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
     * @return The bytes for combineMethod.
     */
    com.google.protobuf.ByteString
        getCombineMethodBytes();
  }
  /**
   * <pre>
   * Configuration for Bidirectional Feature Pyramid Networks.
   * </pre>
   *
   * Protobuf type {@code object_detection.protos.BidirectionalFeaturePyramidNetworks}
   */
  public static final class BidirectionalFeaturePyramidNetworks extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:object_detection.protos.BidirectionalFeaturePyramidNetworks)
      BidirectionalFeaturePyramidNetworksOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BidirectionalFeaturePyramidNetworks.newBuilder() to construct.
    private BidirectionalFeaturePyramidNetworks(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BidirectionalFeaturePyramidNetworks() {
      minLevel_ = 3;
      maxLevel_ = 7;
      combineMethod_ = "fast_attention";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BidirectionalFeaturePyramidNetworks();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BidirectionalFeaturePyramidNetworks(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              minLevel_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              maxLevel_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              numIterations_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              numFilters_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              combineMethod_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return object_detection.protos.Fpn.internal_static_object_detection_protos_BidirectionalFeaturePyramidNetworks_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return object_detection.protos.Fpn.internal_static_object_detection_protos_BidirectionalFeaturePyramidNetworks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks.class, object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks.Builder.class);
    }

    private int bitField0_;
    public static final int MIN_LEVEL_FIELD_NUMBER = 1;
    private int minLevel_;
    /**
     * <pre>
     * minimum level in the feature pyramid.
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     * @return Whether the minLevel field is set.
     */
    @java.lang.Override
    public boolean hasMinLevel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * minimum level in the feature pyramid.
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     * @return The minLevel.
     */
    @java.lang.Override
    public int getMinLevel() {
      return minLevel_;
    }

    public static final int MAX_LEVEL_FIELD_NUMBER = 2;
    private int maxLevel_;
    /**
     * <pre>
     * maximum level in the feature pyramid.
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     * @return Whether the maxLevel field is set.
     */
    @java.lang.Override
    public boolean hasMaxLevel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * maximum level in the feature pyramid.
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     * @return The maxLevel.
     */
    @java.lang.Override
    public int getMaxLevel() {
      return maxLevel_;
    }

    public static final int NUM_ITERATIONS_FIELD_NUMBER = 3;
    private int numIterations_;
    /**
     * <pre>
     * The number of repeated top-down bottom-up iterations for BiFPN-based
     * feature extractors (bidirectional feature pyramid networks).
     * </pre>
     *
     * <code>optional int32 num_iterations = 3;</code>
     * @return Whether the numIterations field is set.
     */
    @java.lang.Override
    public boolean hasNumIterations() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The number of repeated top-down bottom-up iterations for BiFPN-based
     * feature extractors (bidirectional feature pyramid networks).
     * </pre>
     *
     * <code>optional int32 num_iterations = 3;</code>
     * @return The numIterations.
     */
    @java.lang.Override
    public int getNumIterations() {
      return numIterations_;
    }

    public static final int NUM_FILTERS_FIELD_NUMBER = 4;
    private int numFilters_;
    /**
     * <pre>
     * The number of filters (channels) to use in feature pyramid layers for
     * BiFPN-based feature extractors (bidirectional feature pyramid networks).
     * </pre>
     *
     * <code>optional int32 num_filters = 4;</code>
     * @return Whether the numFilters field is set.
     */
    @java.lang.Override
    public boolean hasNumFilters() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * The number of filters (channels) to use in feature pyramid layers for
     * BiFPN-based feature extractors (bidirectional feature pyramid networks).
     * </pre>
     *
     * <code>optional int32 num_filters = 4;</code>
     * @return The numFilters.
     */
    @java.lang.Override
    public int getNumFilters() {
      return numFilters_;
    }

    public static final int COMBINE_METHOD_FIELD_NUMBER = 5;
    private volatile java.lang.Object combineMethod_;
    /**
     * <pre>
     * Method used to combine inputs to BiFPN nodes.
     * </pre>
     *
     * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
     * @return Whether the combineMethod field is set.
     */
    @java.lang.Override
    public boolean hasCombineMethod() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Method used to combine inputs to BiFPN nodes.
     * </pre>
     *
     * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
     * @return The combineMethod.
     */
    @java.lang.Override
    public java.lang.String getCombineMethod() {
      java.lang.Object ref = combineMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          combineMethod_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Method used to combine inputs to BiFPN nodes.
     * </pre>
     *
     * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
     * @return The bytes for combineMethod.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCombineMethodBytes() {
      java.lang.Object ref = combineMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        combineMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, minLevel_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, maxLevel_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, numIterations_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, numFilters_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, combineMethod_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, minLevel_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxLevel_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, numIterations_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, numFilters_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, combineMethod_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks)) {
        return super.equals(obj);
      }
      object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks other = (object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks) obj;

      if (hasMinLevel() != other.hasMinLevel()) return false;
      if (hasMinLevel()) {
        if (getMinLevel()
            != other.getMinLevel()) return false;
      }
      if (hasMaxLevel() != other.hasMaxLevel()) return false;
      if (hasMaxLevel()) {
        if (getMaxLevel()
            != other.getMaxLevel()) return false;
      }
      if (hasNumIterations() != other.hasNumIterations()) return false;
      if (hasNumIterations()) {
        if (getNumIterations()
            != other.getNumIterations()) return false;
      }
      if (hasNumFilters() != other.hasNumFilters()) return false;
      if (hasNumFilters()) {
        if (getNumFilters()
            != other.getNumFilters()) return false;
      }
      if (hasCombineMethod() != other.hasCombineMethod()) return false;
      if (hasCombineMethod()) {
        if (!getCombineMethod()
            .equals(other.getCombineMethod())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMinLevel()) {
        hash = (37 * hash) + MIN_LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getMinLevel();
      }
      if (hasMaxLevel()) {
        hash = (37 * hash) + MAX_LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getMaxLevel();
      }
      if (hasNumIterations()) {
        hash = (37 * hash) + NUM_ITERATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getNumIterations();
      }
      if (hasNumFilters()) {
        hash = (37 * hash) + NUM_FILTERS_FIELD_NUMBER;
        hash = (53 * hash) + getNumFilters();
      }
      if (hasCombineMethod()) {
        hash = (37 * hash) + COMBINE_METHOD_FIELD_NUMBER;
        hash = (53 * hash) + getCombineMethod().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration for Bidirectional Feature Pyramid Networks.
     * </pre>
     *
     * Protobuf type {@code object_detection.protos.BidirectionalFeaturePyramidNetworks}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:object_detection.protos.BidirectionalFeaturePyramidNetworks)
        object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return object_detection.protos.Fpn.internal_static_object_detection_protos_BidirectionalFeaturePyramidNetworks_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return object_detection.protos.Fpn.internal_static_object_detection_protos_BidirectionalFeaturePyramidNetworks_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks.class, object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks.Builder.class);
      }

      // Construct using object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        minLevel_ = 3;
        bitField0_ = (bitField0_ & ~0x00000001);
        maxLevel_ = 7;
        bitField0_ = (bitField0_ & ~0x00000002);
        numIterations_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        numFilters_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        combineMethod_ = "fast_attention";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return object_detection.protos.Fpn.internal_static_object_detection_protos_BidirectionalFeaturePyramidNetworks_descriptor;
      }

      @java.lang.Override
      public object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks getDefaultInstanceForType() {
        return object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks.getDefaultInstance();
      }

      @java.lang.Override
      public object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks build() {
        object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks buildPartial() {
        object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks result = new object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.minLevel_ = minLevel_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.maxLevel_ = maxLevel_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.numIterations_ = numIterations_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.numFilters_ = numFilters_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.combineMethod_ = combineMethod_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks) {
          return mergeFrom((object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks other) {
        if (other == object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks.getDefaultInstance()) return this;
        if (other.hasMinLevel()) {
          setMinLevel(other.getMinLevel());
        }
        if (other.hasMaxLevel()) {
          setMaxLevel(other.getMaxLevel());
        }
        if (other.hasNumIterations()) {
          setNumIterations(other.getNumIterations());
        }
        if (other.hasNumFilters()) {
          setNumFilters(other.getNumFilters());
        }
        if (other.hasCombineMethod()) {
          bitField0_ |= 0x00000010;
          combineMethod_ = other.combineMethod_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int minLevel_ = 3;
      /**
       * <pre>
       * minimum level in the feature pyramid.
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       * @return Whether the minLevel field is set.
       */
      @java.lang.Override
      public boolean hasMinLevel() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * minimum level in the feature pyramid.
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       * @return The minLevel.
       */
      @java.lang.Override
      public int getMinLevel() {
        return minLevel_;
      }
      /**
       * <pre>
       * minimum level in the feature pyramid.
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       * @param value The minLevel to set.
       * @return This builder for chaining.
       */
      public Builder setMinLevel(int value) {
        bitField0_ |= 0x00000001;
        minLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * minimum level in the feature pyramid.
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        minLevel_ = 3;
        onChanged();
        return this;
      }

      private int maxLevel_ = 7;
      /**
       * <pre>
       * maximum level in the feature pyramid.
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       * @return Whether the maxLevel field is set.
       */
      @java.lang.Override
      public boolean hasMaxLevel() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * maximum level in the feature pyramid.
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       * @return The maxLevel.
       */
      @java.lang.Override
      public int getMaxLevel() {
        return maxLevel_;
      }
      /**
       * <pre>
       * maximum level in the feature pyramid.
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       * @param value The maxLevel to set.
       * @return This builder for chaining.
       */
      public Builder setMaxLevel(int value) {
        bitField0_ |= 0x00000002;
        maxLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * maximum level in the feature pyramid.
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxLevel_ = 7;
        onChanged();
        return this;
      }

      private int numIterations_ ;
      /**
       * <pre>
       * The number of repeated top-down bottom-up iterations for BiFPN-based
       * feature extractors (bidirectional feature pyramid networks).
       * </pre>
       *
       * <code>optional int32 num_iterations = 3;</code>
       * @return Whether the numIterations field is set.
       */
      @java.lang.Override
      public boolean hasNumIterations() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * The number of repeated top-down bottom-up iterations for BiFPN-based
       * feature extractors (bidirectional feature pyramid networks).
       * </pre>
       *
       * <code>optional int32 num_iterations = 3;</code>
       * @return The numIterations.
       */
      @java.lang.Override
      public int getNumIterations() {
        return numIterations_;
      }
      /**
       * <pre>
       * The number of repeated top-down bottom-up iterations for BiFPN-based
       * feature extractors (bidirectional feature pyramid networks).
       * </pre>
       *
       * <code>optional int32 num_iterations = 3;</code>
       * @param value The numIterations to set.
       * @return This builder for chaining.
       */
      public Builder setNumIterations(int value) {
        bitField0_ |= 0x00000004;
        numIterations_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The number of repeated top-down bottom-up iterations for BiFPN-based
       * feature extractors (bidirectional feature pyramid networks).
       * </pre>
       *
       * <code>optional int32 num_iterations = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumIterations() {
        bitField0_ = (bitField0_ & ~0x00000004);
        numIterations_ = 0;
        onChanged();
        return this;
      }

      private int numFilters_ ;
      /**
       * <pre>
       * The number of filters (channels) to use in feature pyramid layers for
       * BiFPN-based feature extractors (bidirectional feature pyramid networks).
       * </pre>
       *
       * <code>optional int32 num_filters = 4;</code>
       * @return Whether the numFilters field is set.
       */
      @java.lang.Override
      public boolean hasNumFilters() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * The number of filters (channels) to use in feature pyramid layers for
       * BiFPN-based feature extractors (bidirectional feature pyramid networks).
       * </pre>
       *
       * <code>optional int32 num_filters = 4;</code>
       * @return The numFilters.
       */
      @java.lang.Override
      public int getNumFilters() {
        return numFilters_;
      }
      /**
       * <pre>
       * The number of filters (channels) to use in feature pyramid layers for
       * BiFPN-based feature extractors (bidirectional feature pyramid networks).
       * </pre>
       *
       * <code>optional int32 num_filters = 4;</code>
       * @param value The numFilters to set.
       * @return This builder for chaining.
       */
      public Builder setNumFilters(int value) {
        bitField0_ |= 0x00000008;
        numFilters_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The number of filters (channels) to use in feature pyramid layers for
       * BiFPN-based feature extractors (bidirectional feature pyramid networks).
       * </pre>
       *
       * <code>optional int32 num_filters = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumFilters() {
        bitField0_ = (bitField0_ & ~0x00000008);
        numFilters_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object combineMethod_ = "fast_attention";
      /**
       * <pre>
       * Method used to combine inputs to BiFPN nodes.
       * </pre>
       *
       * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
       * @return Whether the combineMethod field is set.
       */
      public boolean hasCombineMethod() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * Method used to combine inputs to BiFPN nodes.
       * </pre>
       *
       * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
       * @return The combineMethod.
       */
      public java.lang.String getCombineMethod() {
        java.lang.Object ref = combineMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            combineMethod_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Method used to combine inputs to BiFPN nodes.
       * </pre>
       *
       * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
       * @return The bytes for combineMethod.
       */
      public com.google.protobuf.ByteString
          getCombineMethodBytes() {
        java.lang.Object ref = combineMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          combineMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Method used to combine inputs to BiFPN nodes.
       * </pre>
       *
       * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
       * @param value The combineMethod to set.
       * @return This builder for chaining.
       */
      public Builder setCombineMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        combineMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Method used to combine inputs to BiFPN nodes.
       * </pre>
       *
       * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCombineMethod() {
        bitField0_ = (bitField0_ & ~0x00000010);
        combineMethod_ = getDefaultInstance().getCombineMethod();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Method used to combine inputs to BiFPN nodes.
       * </pre>
       *
       * <code>optional string combine_method = 5 [default = "fast_attention"];</code>
       * @param value The bytes for combineMethod to set.
       * @return This builder for chaining.
       */
      public Builder setCombineMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        combineMethod_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:object_detection.protos.BidirectionalFeaturePyramidNetworks)
    }

    // @@protoc_insertion_point(class_scope:object_detection.protos.BidirectionalFeaturePyramidNetworks)
    private static final object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks();
    }

    public static object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BidirectionalFeaturePyramidNetworks>
        PARSER = new com.google.protobuf.AbstractParser<BidirectionalFeaturePyramidNetworks>() {
      @java.lang.Override
      public BidirectionalFeaturePyramidNetworks parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BidirectionalFeaturePyramidNetworks(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BidirectionalFeaturePyramidNetworks> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BidirectionalFeaturePyramidNetworks> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public object_detection.protos.Fpn.BidirectionalFeaturePyramidNetworks getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_object_detection_protos_FeaturePyramidNetworks_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_object_detection_protos_FeaturePyramidNetworks_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_object_detection_protos_BidirectionalFeaturePyramidNetworks_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_object_detection_protos_BidirectionalFeaturePyramidNetworks_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!object_detection/protos/fpn.proto\022\027obj" +
      "ect_detection.protos\"i\n\026FeaturePyramidNe" +
      "tworks\022\024\n\tmin_level\030\001 \001(\005:\0013\022\024\n\tmax_leve" +
      "l\030\002 \001(\005:\0017\022#\n\026additional_layer_depth\030\003 \001" +
      "(\005:\003256\"\246\001\n#BidirectionalFeaturePyramidN" +
      "etworks\022\024\n\tmin_level\030\001 \001(\005:\0013\022\024\n\tmax_lev" +
      "el\030\002 \001(\005:\0017\022\026\n\016num_iterations\030\003 \001(\005\022\023\n\013n" +
      "um_filters\030\004 \001(\005\022&\n\016combine_method\030\005 \001(\t" +
      ":\016fast_attention"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_object_detection_protos_FeaturePyramidNetworks_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_object_detection_protos_FeaturePyramidNetworks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_object_detection_protos_FeaturePyramidNetworks_descriptor,
        new java.lang.String[] { "MinLevel", "MaxLevel", "AdditionalLayerDepth", });
    internal_static_object_detection_protos_BidirectionalFeaturePyramidNetworks_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_object_detection_protos_BidirectionalFeaturePyramidNetworks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_object_detection_protos_BidirectionalFeaturePyramidNetworks_descriptor,
        new java.lang.String[] { "MinLevel", "MaxLevel", "NumIterations", "NumFilters", "CombineMethod", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
