/*
 * Copyright (c) 2020. Kin-Hong Wong. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/grid_anchor_generator.proto

package object_detection.protos;

public final class GridAnchorGeneratorOuterClass {
  private GridAnchorGeneratorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GridAnchorGeneratorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:object_detection.protos.GridAnchorGenerator)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Anchor height in pixels.
     * </pre>
     *
     * <code>optional int32 height = 1 [default = 256];</code>
     * @return Whether the height field is set.
     */
    boolean hasHeight();
    /**
     * <pre>
     * Anchor height in pixels.
     * </pre>
     *
     * <code>optional int32 height = 1 [default = 256];</code>
     * @return The height.
     */
    int getHeight();

    /**
     * <pre>
     * Anchor width in pixels.
     * </pre>
     *
     * <code>optional int32 width = 2 [default = 256];</code>
     * @return Whether the width field is set.
     */
    boolean hasWidth();
    /**
     * <pre>
     * Anchor width in pixels.
     * </pre>
     *
     * <code>optional int32 width = 2 [default = 256];</code>
     * @return The width.
     */
    int getWidth();

    /**
     * <pre>
     * Anchor stride in height dimension in pixels.
     * </pre>
     *
     * <code>optional int32 height_stride = 3 [default = 16];</code>
     * @return Whether the heightStride field is set.
     */
    boolean hasHeightStride();
    /**
     * <pre>
     * Anchor stride in height dimension in pixels.
     * </pre>
     *
     * <code>optional int32 height_stride = 3 [default = 16];</code>
     * @return The heightStride.
     */
    int getHeightStride();

    /**
     * <pre>
     * Anchor stride in width dimension in pixels.
     * </pre>
     *
     * <code>optional int32 width_stride = 4 [default = 16];</code>
     * @return Whether the widthStride field is set.
     */
    boolean hasWidthStride();
    /**
     * <pre>
     * Anchor stride in width dimension in pixels.
     * </pre>
     *
     * <code>optional int32 width_stride = 4 [default = 16];</code>
     * @return The widthStride.
     */
    int getWidthStride();

    /**
     * <pre>
     * Anchor height offset in pixels.
     * </pre>
     *
     * <code>optional int32 height_offset = 5 [default = 0];</code>
     * @return Whether the heightOffset field is set.
     */
    boolean hasHeightOffset();
    /**
     * <pre>
     * Anchor height offset in pixels.
     * </pre>
     *
     * <code>optional int32 height_offset = 5 [default = 0];</code>
     * @return The heightOffset.
     */
    int getHeightOffset();

    /**
     * <pre>
     * Anchor width offset in pixels.
     * </pre>
     *
     * <code>optional int32 width_offset = 6 [default = 0];</code>
     * @return Whether the widthOffset field is set.
     */
    boolean hasWidthOffset();
    /**
     * <pre>
     * Anchor width offset in pixels.
     * </pre>
     *
     * <code>optional int32 width_offset = 6 [default = 0];</code>
     * @return The widthOffset.
     */
    int getWidthOffset();

    /**
     * <pre>
     * List of scales for the anchors.
     * </pre>
     *
     * <code>repeated float scales = 7;</code>
     * @return A list containing the scales.
     */
    java.util.List<java.lang.Float> getScalesList();
    /**
     * <pre>
     * List of scales for the anchors.
     * </pre>
     *
     * <code>repeated float scales = 7;</code>
     * @return The count of scales.
     */
    int getScalesCount();
    /**
     * <pre>
     * List of scales for the anchors.
     * </pre>
     *
     * <code>repeated float scales = 7;</code>
     * @param index The index of the element to return.
     * @return The scales at the given index.
     */
    float getScales(int index);

    /**
     * <pre>
     * List of aspect ratios for the anchors.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 8;</code>
     * @return A list containing the aspectRatios.
     */
    java.util.List<java.lang.Float> getAspectRatiosList();
    /**
     * <pre>
     * List of aspect ratios for the anchors.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 8;</code>
     * @return The count of aspectRatios.
     */
    int getAspectRatiosCount();
    /**
     * <pre>
     * List of aspect ratios for the anchors.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 8;</code>
     * @param index The index of the element to return.
     * @return The aspectRatios at the given index.
     */
    float getAspectRatios(int index);
  }
  /**
   * <pre>
   * Configuration proto for GridAnchorGenerator. See
   * anchor_generators/grid_anchor_generator.py for details.
   * </pre>
   *
   * Protobuf type {@code object_detection.protos.GridAnchorGenerator}
   */
  public static final class GridAnchorGenerator extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:object_detection.protos.GridAnchorGenerator)
      GridAnchorGeneratorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GridAnchorGenerator.newBuilder() to construct.
    private GridAnchorGenerator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GridAnchorGenerator() {
      height_ = 256;
      width_ = 256;
      heightStride_ = 16;
      widthStride_ = 16;
      scales_ = emptyFloatList();
      aspectRatios_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GridAnchorGenerator();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GridAnchorGenerator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              height_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              width_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              heightStride_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              widthStride_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              heightOffset_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              widthOffset_ = input.readInt32();
              break;
            }
            case 61: {
              if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                scales_ = newFloatList();
                mutable_bitField0_ |= 0x00000040;
              }
              scales_.addFloat(input.readFloat());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000040) != 0) && input.getBytesUntilLimit() > 0) {
                scales_ = newFloatList();
                mutable_bitField0_ |= 0x00000040;
              }
              while (input.getBytesUntilLimit() > 0) {
                scales_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 69: {
              if (!((mutable_bitField0_ & 0x00000080) != 0)) {
                aspectRatios_ = newFloatList();
                mutable_bitField0_ |= 0x00000080;
              }
              aspectRatios_.addFloat(input.readFloat());
              break;
            }
            case 66: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000080) != 0) && input.getBytesUntilLimit() > 0) {
                aspectRatios_ = newFloatList();
                mutable_bitField0_ |= 0x00000080;
              }
              while (input.getBytesUntilLimit() > 0) {
                aspectRatios_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) != 0)) {
          scales_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000080) != 0)) {
          aspectRatios_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return object_detection.protos.GridAnchorGeneratorOuterClass.internal_static_object_detection_protos_GridAnchorGenerator_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return object_detection.protos.GridAnchorGeneratorOuterClass.internal_static_object_detection_protos_GridAnchorGenerator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.class, object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.Builder.class);
    }

    private int bitField0_;
    public static final int HEIGHT_FIELD_NUMBER = 1;
    private int height_;
    /**
     * <pre>
     * Anchor height in pixels.
     * </pre>
     *
     * <code>optional int32 height = 1 [default = 256];</code>
     * @return Whether the height field is set.
     */
    @java.lang.Override
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Anchor height in pixels.
     * </pre>
     *
     * <code>optional int32 height = 1 [default = 256];</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    public static final int WIDTH_FIELD_NUMBER = 2;
    private int width_;
    /**
     * <pre>
     * Anchor width in pixels.
     * </pre>
     *
     * <code>optional int32 width = 2 [default = 256];</code>
     * @return Whether the width field is set.
     */
    @java.lang.Override
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Anchor width in pixels.
     * </pre>
     *
     * <code>optional int32 width = 2 [default = 256];</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_STRIDE_FIELD_NUMBER = 3;
    private int heightStride_;
    /**
     * <pre>
     * Anchor stride in height dimension in pixels.
     * </pre>
     *
     * <code>optional int32 height_stride = 3 [default = 16];</code>
     * @return Whether the heightStride field is set.
     */
    @java.lang.Override
    public boolean hasHeightStride() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Anchor stride in height dimension in pixels.
     * </pre>
     *
     * <code>optional int32 height_stride = 3 [default = 16];</code>
     * @return The heightStride.
     */
    @java.lang.Override
    public int getHeightStride() {
      return heightStride_;
    }

    public static final int WIDTH_STRIDE_FIELD_NUMBER = 4;
    private int widthStride_;
    /**
     * <pre>
     * Anchor stride in width dimension in pixels.
     * </pre>
     *
     * <code>optional int32 width_stride = 4 [default = 16];</code>
     * @return Whether the widthStride field is set.
     */
    @java.lang.Override
    public boolean hasWidthStride() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Anchor stride in width dimension in pixels.
     * </pre>
     *
     * <code>optional int32 width_stride = 4 [default = 16];</code>
     * @return The widthStride.
     */
    @java.lang.Override
    public int getWidthStride() {
      return widthStride_;
    }

    public static final int HEIGHT_OFFSET_FIELD_NUMBER = 5;
    private int heightOffset_;
    /**
     * <pre>
     * Anchor height offset in pixels.
     * </pre>
     *
     * <code>optional int32 height_offset = 5 [default = 0];</code>
     * @return Whether the heightOffset field is set.
     */
    @java.lang.Override
    public boolean hasHeightOffset() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Anchor height offset in pixels.
     * </pre>
     *
     * <code>optional int32 height_offset = 5 [default = 0];</code>
     * @return The heightOffset.
     */
    @java.lang.Override
    public int getHeightOffset() {
      return heightOffset_;
    }

    public static final int WIDTH_OFFSET_FIELD_NUMBER = 6;
    private int widthOffset_;
    /**
     * <pre>
     * Anchor width offset in pixels.
     * </pre>
     *
     * <code>optional int32 width_offset = 6 [default = 0];</code>
     * @return Whether the widthOffset field is set.
     */
    @java.lang.Override
    public boolean hasWidthOffset() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Anchor width offset in pixels.
     * </pre>
     *
     * <code>optional int32 width_offset = 6 [default = 0];</code>
     * @return The widthOffset.
     */
    @java.lang.Override
    public int getWidthOffset() {
      return widthOffset_;
    }

    public static final int SCALES_FIELD_NUMBER = 7;
    private com.google.protobuf.Internal.FloatList scales_;
    /**
     * <pre>
     * List of scales for the anchors.
     * </pre>
     *
     * <code>repeated float scales = 7;</code>
     * @return A list containing the scales.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getScalesList() {
      return scales_;
    }
    /**
     * <pre>
     * List of scales for the anchors.
     * </pre>
     *
     * <code>repeated float scales = 7;</code>
     * @return The count of scales.
     */
    public int getScalesCount() {
      return scales_.size();
    }
    /**
     * <pre>
     * List of scales for the anchors.
     * </pre>
     *
     * <code>repeated float scales = 7;</code>
     * @param index The index of the element to return.
     * @return The scales at the given index.
     */
    public float getScales(int index) {
      return scales_.getFloat(index);
    }

    public static final int ASPECT_RATIOS_FIELD_NUMBER = 8;
    private com.google.protobuf.Internal.FloatList aspectRatios_;
    /**
     * <pre>
     * List of aspect ratios for the anchors.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 8;</code>
     * @return A list containing the aspectRatios.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getAspectRatiosList() {
      return aspectRatios_;
    }
    /**
     * <pre>
     * List of aspect ratios for the anchors.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 8;</code>
     * @return The count of aspectRatios.
     */
    public int getAspectRatiosCount() {
      return aspectRatios_.size();
    }
    /**
     * <pre>
     * List of aspect ratios for the anchors.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 8;</code>
     * @param index The index of the element to return.
     * @return The aspectRatios at the given index.
     */
    public float getAspectRatios(int index) {
      return aspectRatios_.getFloat(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, height_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, width_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, heightStride_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, widthStride_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, heightOffset_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, widthOffset_);
      }
      for (int i = 0; i < scales_.size(); i++) {
        output.writeFloat(7, scales_.getFloat(i));
      }
      for (int i = 0; i < aspectRatios_.size(); i++) {
        output.writeFloat(8, aspectRatios_.getFloat(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, height_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, width_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, heightStride_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, widthStride_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, heightOffset_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, widthOffset_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getScalesList().size();
        size += dataSize;
        size += 1 * getScalesList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getAspectRatiosList().size();
        size += dataSize;
        size += 1 * getAspectRatiosList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator)) {
        return super.equals(obj);
      }
      object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator other = (object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) obj;

      if (hasHeight() != other.hasHeight()) return false;
      if (hasHeight()) {
        if (getHeight()
            != other.getHeight()) return false;
      }
      if (hasWidth() != other.hasWidth()) return false;
      if (hasWidth()) {
        if (getWidth()
            != other.getWidth()) return false;
      }
      if (hasHeightStride() != other.hasHeightStride()) return false;
      if (hasHeightStride()) {
        if (getHeightStride()
            != other.getHeightStride()) return false;
      }
      if (hasWidthStride() != other.hasWidthStride()) return false;
      if (hasWidthStride()) {
        if (getWidthStride()
            != other.getWidthStride()) return false;
      }
      if (hasHeightOffset() != other.hasHeightOffset()) return false;
      if (hasHeightOffset()) {
        if (getHeightOffset()
            != other.getHeightOffset()) return false;
      }
      if (hasWidthOffset() != other.hasWidthOffset()) return false;
      if (hasWidthOffset()) {
        if (getWidthOffset()
            != other.getWidthOffset()) return false;
      }
      if (!getScalesList()
          .equals(other.getScalesList())) return false;
      if (!getAspectRatiosList()
          .equals(other.getAspectRatiosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeight()) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeight();
      }
      if (hasWidth()) {
        hash = (37 * hash) + WIDTH_FIELD_NUMBER;
        hash = (53 * hash) + getWidth();
      }
      if (hasHeightStride()) {
        hash = (37 * hash) + HEIGHT_STRIDE_FIELD_NUMBER;
        hash = (53 * hash) + getHeightStride();
      }
      if (hasWidthStride()) {
        hash = (37 * hash) + WIDTH_STRIDE_FIELD_NUMBER;
        hash = (53 * hash) + getWidthStride();
      }
      if (hasHeightOffset()) {
        hash = (37 * hash) + HEIGHT_OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + getHeightOffset();
      }
      if (hasWidthOffset()) {
        hash = (37 * hash) + WIDTH_OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + getWidthOffset();
      }
      if (getScalesCount() > 0) {
        hash = (37 * hash) + SCALES_FIELD_NUMBER;
        hash = (53 * hash) + getScalesList().hashCode();
      }
      if (getAspectRatiosCount() > 0) {
        hash = (37 * hash) + ASPECT_RATIOS_FIELD_NUMBER;
        hash = (53 * hash) + getAspectRatiosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration proto for GridAnchorGenerator. See
     * anchor_generators/grid_anchor_generator.py for details.
     * </pre>
     *
     * Protobuf type {@code object_detection.protos.GridAnchorGenerator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:object_detection.protos.GridAnchorGenerator)
        object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGeneratorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return object_detection.protos.GridAnchorGeneratorOuterClass.internal_static_object_detection_protos_GridAnchorGenerator_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return object_detection.protos.GridAnchorGeneratorOuterClass.internal_static_object_detection_protos_GridAnchorGenerator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.class, object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.Builder.class);
      }

      // Construct using object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        height_ = 256;
        bitField0_ = (bitField0_ & ~0x00000001);
        width_ = 256;
        bitField0_ = (bitField0_ & ~0x00000002);
        heightStride_ = 16;
        bitField0_ = (bitField0_ & ~0x00000004);
        widthStride_ = 16;
        bitField0_ = (bitField0_ & ~0x00000008);
        heightOffset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        widthOffset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        scales_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000040);
        aspectRatios_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return object_detection.protos.GridAnchorGeneratorOuterClass.internal_static_object_detection_protos_GridAnchorGenerator_descriptor;
      }

      @java.lang.Override
      public object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator getDefaultInstanceForType() {
        return object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.getDefaultInstance();
      }

      @java.lang.Override
      public object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator build() {
        object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator buildPartial() {
        object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator result = new object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.heightStride_ = heightStride_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.widthStride_ = widthStride_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.heightOffset_ = heightOffset_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.widthOffset_ = widthOffset_;
          to_bitField0_ |= 0x00000020;
        }
        if (((bitField0_ & 0x00000040) != 0)) {
          scales_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.scales_ = scales_;
        if (((bitField0_ & 0x00000080) != 0)) {
          aspectRatios_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.aspectRatios_ = aspectRatios_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) {
          return mergeFrom((object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator other) {
        if (other == object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator.getDefaultInstance()) return this;
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeightStride()) {
          setHeightStride(other.getHeightStride());
        }
        if (other.hasWidthStride()) {
          setWidthStride(other.getWidthStride());
        }
        if (other.hasHeightOffset()) {
          setHeightOffset(other.getHeightOffset());
        }
        if (other.hasWidthOffset()) {
          setWidthOffset(other.getWidthOffset());
        }
        if (!other.scales_.isEmpty()) {
          if (scales_.isEmpty()) {
            scales_ = other.scales_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureScalesIsMutable();
            scales_.addAll(other.scales_);
          }
          onChanged();
        }
        if (!other.aspectRatios_.isEmpty()) {
          if (aspectRatios_.isEmpty()) {
            aspectRatios_ = other.aspectRatios_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureAspectRatiosIsMutable();
            aspectRatios_.addAll(other.aspectRatios_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int height_ = 256;
      /**
       * <pre>
       * Anchor height in pixels.
       * </pre>
       *
       * <code>optional int32 height = 1 [default = 256];</code>
       * @return Whether the height field is set.
       */
      @java.lang.Override
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Anchor height in pixels.
       * </pre>
       *
       * <code>optional int32 height = 1 [default = 256];</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <pre>
       * Anchor height in pixels.
       * </pre>
       *
       * <code>optional int32 height = 1 [default = 256];</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000001;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Anchor height in pixels.
       * </pre>
       *
       * <code>optional int32 height = 1 [default = 256];</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000001);
        height_ = 256;
        onChanged();
        return this;
      }

      private int width_ = 256;
      /**
       * <pre>
       * Anchor width in pixels.
       * </pre>
       *
       * <code>optional int32 width = 2 [default = 256];</code>
       * @return Whether the width field is set.
       */
      @java.lang.Override
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Anchor width in pixels.
       * </pre>
       *
       * <code>optional int32 width = 2 [default = 256];</code>
       * @return The width.
       */
      @java.lang.Override
      public int getWidth() {
        return width_;
      }
      /**
       * <pre>
       * Anchor width in pixels.
       * </pre>
       *
       * <code>optional int32 width = 2 [default = 256];</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000002;
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Anchor width in pixels.
       * </pre>
       *
       * <code>optional int32 width = 2 [default = 256];</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        width_ = 256;
        onChanged();
        return this;
      }

      private int heightStride_ = 16;
      /**
       * <pre>
       * Anchor stride in height dimension in pixels.
       * </pre>
       *
       * <code>optional int32 height_stride = 3 [default = 16];</code>
       * @return Whether the heightStride field is set.
       */
      @java.lang.Override
      public boolean hasHeightStride() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Anchor stride in height dimension in pixels.
       * </pre>
       *
       * <code>optional int32 height_stride = 3 [default = 16];</code>
       * @return The heightStride.
       */
      @java.lang.Override
      public int getHeightStride() {
        return heightStride_;
      }
      /**
       * <pre>
       * Anchor stride in height dimension in pixels.
       * </pre>
       *
       * <code>optional int32 height_stride = 3 [default = 16];</code>
       * @param value The heightStride to set.
       * @return This builder for chaining.
       */
      public Builder setHeightStride(int value) {
        bitField0_ |= 0x00000004;
        heightStride_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Anchor stride in height dimension in pixels.
       * </pre>
       *
       * <code>optional int32 height_stride = 3 [default = 16];</code>
       * @return This builder for chaining.
       */
      public Builder clearHeightStride() {
        bitField0_ = (bitField0_ & ~0x00000004);
        heightStride_ = 16;
        onChanged();
        return this;
      }

      private int widthStride_ = 16;
      /**
       * <pre>
       * Anchor stride in width dimension in pixels.
       * </pre>
       *
       * <code>optional int32 width_stride = 4 [default = 16];</code>
       * @return Whether the widthStride field is set.
       */
      @java.lang.Override
      public boolean hasWidthStride() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Anchor stride in width dimension in pixels.
       * </pre>
       *
       * <code>optional int32 width_stride = 4 [default = 16];</code>
       * @return The widthStride.
       */
      @java.lang.Override
      public int getWidthStride() {
        return widthStride_;
      }
      /**
       * <pre>
       * Anchor stride in width dimension in pixels.
       * </pre>
       *
       * <code>optional int32 width_stride = 4 [default = 16];</code>
       * @param value The widthStride to set.
       * @return This builder for chaining.
       */
      public Builder setWidthStride(int value) {
        bitField0_ |= 0x00000008;
        widthStride_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Anchor stride in width dimension in pixels.
       * </pre>
       *
       * <code>optional int32 width_stride = 4 [default = 16];</code>
       * @return This builder for chaining.
       */
      public Builder clearWidthStride() {
        bitField0_ = (bitField0_ & ~0x00000008);
        widthStride_ = 16;
        onChanged();
        return this;
      }

      private int heightOffset_ ;
      /**
       * <pre>
       * Anchor height offset in pixels.
       * </pre>
       *
       * <code>optional int32 height_offset = 5 [default = 0];</code>
       * @return Whether the heightOffset field is set.
       */
      @java.lang.Override
      public boolean hasHeightOffset() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * Anchor height offset in pixels.
       * </pre>
       *
       * <code>optional int32 height_offset = 5 [default = 0];</code>
       * @return The heightOffset.
       */
      @java.lang.Override
      public int getHeightOffset() {
        return heightOffset_;
      }
      /**
       * <pre>
       * Anchor height offset in pixels.
       * </pre>
       *
       * <code>optional int32 height_offset = 5 [default = 0];</code>
       * @param value The heightOffset to set.
       * @return This builder for chaining.
       */
      public Builder setHeightOffset(int value) {
        bitField0_ |= 0x00000010;
        heightOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Anchor height offset in pixels.
       * </pre>
       *
       * <code>optional int32 height_offset = 5 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearHeightOffset() {
        bitField0_ = (bitField0_ & ~0x00000010);
        heightOffset_ = 0;
        onChanged();
        return this;
      }

      private int widthOffset_ ;
      /**
       * <pre>
       * Anchor width offset in pixels.
       * </pre>
       *
       * <code>optional int32 width_offset = 6 [default = 0];</code>
       * @return Whether the widthOffset field is set.
       */
      @java.lang.Override
      public boolean hasWidthOffset() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * Anchor width offset in pixels.
       * </pre>
       *
       * <code>optional int32 width_offset = 6 [default = 0];</code>
       * @return The widthOffset.
       */
      @java.lang.Override
      public int getWidthOffset() {
        return widthOffset_;
      }
      /**
       * <pre>
       * Anchor width offset in pixels.
       * </pre>
       *
       * <code>optional int32 width_offset = 6 [default = 0];</code>
       * @param value The widthOffset to set.
       * @return This builder for chaining.
       */
      public Builder setWidthOffset(int value) {
        bitField0_ |= 0x00000020;
        widthOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Anchor width offset in pixels.
       * </pre>
       *
       * <code>optional int32 width_offset = 6 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearWidthOffset() {
        bitField0_ = (bitField0_ & ~0x00000020);
        widthOffset_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList scales_ = emptyFloatList();
      private void ensureScalesIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          scales_ = mutableCopy(scales_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <pre>
       * List of scales for the anchors.
       * </pre>
       *
       * <code>repeated float scales = 7;</code>
       * @return A list containing the scales.
       */
      public java.util.List<java.lang.Float>
          getScalesList() {
        return ((bitField0_ & 0x00000040) != 0) ?
                 java.util.Collections.unmodifiableList(scales_) : scales_;
      }
      /**
       * <pre>
       * List of scales for the anchors.
       * </pre>
       *
       * <code>repeated float scales = 7;</code>
       * @return The count of scales.
       */
      public int getScalesCount() {
        return scales_.size();
      }
      /**
       * <pre>
       * List of scales for the anchors.
       * </pre>
       *
       * <code>repeated float scales = 7;</code>
       * @param index The index of the element to return.
       * @return The scales at the given index.
       */
      public float getScales(int index) {
        return scales_.getFloat(index);
      }
      /**
       * <pre>
       * List of scales for the anchors.
       * </pre>
       *
       * <code>repeated float scales = 7;</code>
       * @param index The index to set the value at.
       * @param value The scales to set.
       * @return This builder for chaining.
       */
      public Builder setScales(
          int index, float value) {
        ensureScalesIsMutable();
        scales_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of scales for the anchors.
       * </pre>
       *
       * <code>repeated float scales = 7;</code>
       * @param value The scales to add.
       * @return This builder for chaining.
       */
      public Builder addScales(float value) {
        ensureScalesIsMutable();
        scales_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of scales for the anchors.
       * </pre>
       *
       * <code>repeated float scales = 7;</code>
       * @param values The scales to add.
       * @return This builder for chaining.
       */
      public Builder addAllScales(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureScalesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scales_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of scales for the anchors.
       * </pre>
       *
       * <code>repeated float scales = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearScales() {
        scales_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList aspectRatios_ = emptyFloatList();
      private void ensureAspectRatiosIsMutable() {
        if (!((bitField0_ & 0x00000080) != 0)) {
          aspectRatios_ = mutableCopy(aspectRatios_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <pre>
       * List of aspect ratios for the anchors.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 8;</code>
       * @return A list containing the aspectRatios.
       */
      public java.util.List<java.lang.Float>
          getAspectRatiosList() {
        return ((bitField0_ & 0x00000080) != 0) ?
                 java.util.Collections.unmodifiableList(aspectRatios_) : aspectRatios_;
      }
      /**
       * <pre>
       * List of aspect ratios for the anchors.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 8;</code>
       * @return The count of aspectRatios.
       */
      public int getAspectRatiosCount() {
        return aspectRatios_.size();
      }
      /**
       * <pre>
       * List of aspect ratios for the anchors.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 8;</code>
       * @param index The index of the element to return.
       * @return The aspectRatios at the given index.
       */
      public float getAspectRatios(int index) {
        return aspectRatios_.getFloat(index);
      }
      /**
       * <pre>
       * List of aspect ratios for the anchors.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 8;</code>
       * @param index The index to set the value at.
       * @param value The aspectRatios to set.
       * @return This builder for chaining.
       */
      public Builder setAspectRatios(
          int index, float value) {
        ensureAspectRatiosIsMutable();
        aspectRatios_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of aspect ratios for the anchors.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 8;</code>
       * @param value The aspectRatios to add.
       * @return This builder for chaining.
       */
      public Builder addAspectRatios(float value) {
        ensureAspectRatiosIsMutable();
        aspectRatios_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of aspect ratios for the anchors.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 8;</code>
       * @param values The aspectRatios to add.
       * @return This builder for chaining.
       */
      public Builder addAllAspectRatios(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureAspectRatiosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aspectRatios_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of aspect ratios for the anchors.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearAspectRatios() {
        aspectRatios_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:object_detection.protos.GridAnchorGenerator)
    }

    // @@protoc_insertion_point(class_scope:object_detection.protos.GridAnchorGenerator)
    private static final object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator();
    }

    public static object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GridAnchorGenerator>
        PARSER = new com.google.protobuf.AbstractParser<GridAnchorGenerator>() {
      @java.lang.Override
      public GridAnchorGenerator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GridAnchorGenerator(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GridAnchorGenerator> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GridAnchorGenerator> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public object_detection.protos.GridAnchorGeneratorOuterClass.GridAnchorGenerator getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_object_detection_protos_GridAnchorGenerator_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_object_detection_protos_GridAnchorGenerator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3object_detection/protos/grid_anchor_ge" +
      "nerator.proto\022\027object_detection.protos\"\315" +
      "\001\n\023GridAnchorGenerator\022\023\n\006height\030\001 \001(\005:\003" +
      "256\022\022\n\005width\030\002 \001(\005:\003256\022\031\n\rheight_stride" +
      "\030\003 \001(\005:\00216\022\030\n\014width_stride\030\004 \001(\005:\00216\022\030\n\r" +
      "height_offset\030\005 \001(\005:\0010\022\027\n\014width_offset\030\006" +
      " \001(\005:\0010\022\016\n\006scales\030\007 \003(\002\022\025\n\raspect_ratios" +
      "\030\010 \003(\002"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_object_detection_protos_GridAnchorGenerator_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_object_detection_protos_GridAnchorGenerator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_object_detection_protos_GridAnchorGenerator_descriptor,
        new java.lang.String[] { "Height", "Width", "HeightStride", "WidthStride", "HeightOffset", "WidthOffset", "Scales", "AspectRatios", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
