/*
 * Copyright (c) 2019. Kin-Hong Wong. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ==============================================================================
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/multiscale_anchor_generator.proto

package object_detection.protos;

public final class MultiscaleAnchorGeneratorOuterClass {
  private MultiscaleAnchorGeneratorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MultiscaleAnchorGeneratorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:object_detection.protos.MultiscaleAnchorGenerator)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * minimum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     */
    boolean hasMinLevel();
    /**
     * <pre>
     * minimum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     */
    int getMinLevel();

    /**
     * <pre>
     * maximum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     */
    boolean hasMaxLevel();
    /**
     * <pre>
     * maximum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     */
    int getMaxLevel();

    /**
     * <pre>
     * Scale of anchor to feature stride
     * </pre>
     *
     * <code>optional float anchor_scale = 3 [default = 4];</code>
     */
    boolean hasAnchorScale();
    /**
     * <pre>
     * Scale of anchor to feature stride
     * </pre>
     *
     * <code>optional float anchor_scale = 3 [default = 4];</code>
     */
    float getAnchorScale();

    /**
     * <pre>
     * Aspect ratios for anchors at each grid point.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 4;</code>
     */
    java.util.List<java.lang.Float> getAspectRatiosList();
    /**
     * <pre>
     * Aspect ratios for anchors at each grid point.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 4;</code>
     */
    int getAspectRatiosCount();
    /**
     * <pre>
     * Aspect ratios for anchors at each grid point.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 4;</code>
     */
    float getAspectRatios(int index);

    /**
     * <pre>
     * Number of intermediate scale each scale octave
     * </pre>
     *
     * <code>optional int32 scales_per_octave = 5 [default = 2];</code>
     */
    boolean hasScalesPerOctave();
    /**
     * <pre>
     * Number of intermediate scale each scale octave
     * </pre>
     *
     * <code>optional int32 scales_per_octave = 5 [default = 2];</code>
     */
    int getScalesPerOctave();

    /**
     * <pre>
     * Whether to produce anchors in normalized coordinates.
     * </pre>
     *
     * <code>optional bool normalize_coordinates = 6 [default = true];</code>
     */
    boolean hasNormalizeCoordinates();
    /**
     * <pre>
     * Whether to produce anchors in normalized coordinates.
     * </pre>
     *
     * <code>optional bool normalize_coordinates = 6 [default = true];</code>
     */
    boolean getNormalizeCoordinates();
  }
  /**
   * <pre>
   * Configuration proto for RetinaNet anchor generator described in
   * https://arxiv.org/abs/1708.02002. See
   * anchor_generators/multiscale_grid_anchor_generator.py for details.
   * </pre>
   *
   * Protobuf type {@code object_detection.protos.MultiscaleAnchorGenerator}
   */
  public  static final class MultiscaleAnchorGenerator extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:object_detection.protos.MultiscaleAnchorGenerator)
      MultiscaleAnchorGeneratorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultiscaleAnchorGenerator.newBuilder() to construct.
    private MultiscaleAnchorGenerator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiscaleAnchorGenerator() {
      minLevel_ = 3;
      maxLevel_ = 7;
      anchorScale_ = 4F;
      aspectRatios_ = java.util.Collections.emptyList();
      scalesPerOctave_ = 2;
      normalizeCoordinates_ = true;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiscaleAnchorGenerator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              minLevel_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              maxLevel_ = input.readInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              anchorScale_ = input.readFloat();
              break;
            }
            case 37: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                aspectRatios_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000008;
              }
              aspectRatios_.add(input.readFloat());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                aspectRatios_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                aspectRatios_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              scalesPerOctave_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              normalizeCoordinates_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          aspectRatios_ = java.util.Collections.unmodifiableList(aspectRatios_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.internal_static_object_detection_protos_MultiscaleAnchorGenerator_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.internal_static_object_detection_protos_MultiscaleAnchorGenerator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.class, object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.Builder.class);
    }

    private int bitField0_;
    public static final int MIN_LEVEL_FIELD_NUMBER = 1;
    private int minLevel_;
    /**
     * <pre>
     * minimum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     */
    public boolean hasMinLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * minimum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 min_level = 1 [default = 3];</code>
     */
    public int getMinLevel() {
      return minLevel_;
    }

    public static final int MAX_LEVEL_FIELD_NUMBER = 2;
    private int maxLevel_;
    /**
     * <pre>
     * maximum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     */
    public boolean hasMaxLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * maximum level in feature pyramid
     * </pre>
     *
     * <code>optional int32 max_level = 2 [default = 7];</code>
     */
    public int getMaxLevel() {
      return maxLevel_;
    }

    public static final int ANCHOR_SCALE_FIELD_NUMBER = 3;
    private float anchorScale_;
    /**
     * <pre>
     * Scale of anchor to feature stride
     * </pre>
     *
     * <code>optional float anchor_scale = 3 [default = 4];</code>
     */
    public boolean hasAnchorScale() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Scale of anchor to feature stride
     * </pre>
     *
     * <code>optional float anchor_scale = 3 [default = 4];</code>
     */
    public float getAnchorScale() {
      return anchorScale_;
    }

    public static final int ASPECT_RATIOS_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Float> aspectRatios_;
    /**
     * <pre>
     * Aspect ratios for anchors at each grid point.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 4;</code>
     */
    public java.util.List<java.lang.Float>
        getAspectRatiosList() {
      return aspectRatios_;
    }
    /**
     * <pre>
     * Aspect ratios for anchors at each grid point.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 4;</code>
     */
    public int getAspectRatiosCount() {
      return aspectRatios_.size();
    }
    /**
     * <pre>
     * Aspect ratios for anchors at each grid point.
     * </pre>
     *
     * <code>repeated float aspect_ratios = 4;</code>
     */
    public float getAspectRatios(int index) {
      return aspectRatios_.get(index);
    }

    public static final int SCALES_PER_OCTAVE_FIELD_NUMBER = 5;
    private int scalesPerOctave_;
    /**
     * <pre>
     * Number of intermediate scale each scale octave
     * </pre>
     *
     * <code>optional int32 scales_per_octave = 5 [default = 2];</code>
     */
    public boolean hasScalesPerOctave() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * Number of intermediate scale each scale octave
     * </pre>
     *
     * <code>optional int32 scales_per_octave = 5 [default = 2];</code>
     */
    public int getScalesPerOctave() {
      return scalesPerOctave_;
    }

    public static final int NORMALIZE_COORDINATES_FIELD_NUMBER = 6;
    private boolean normalizeCoordinates_;
    /**
     * <pre>
     * Whether to produce anchors in normalized coordinates.
     * </pre>
     *
     * <code>optional bool normalize_coordinates = 6 [default = true];</code>
     */
    public boolean hasNormalizeCoordinates() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * Whether to produce anchors in normalized coordinates.
     * </pre>
     *
     * <code>optional bool normalize_coordinates = 6 [default = true];</code>
     */
    public boolean getNormalizeCoordinates() {
      return normalizeCoordinates_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, minLevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, maxLevel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, anchorScale_);
      }
      for (int i = 0; i < aspectRatios_.size(); i++) {
        output.writeFloat(4, aspectRatios_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, scalesPerOctave_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(6, normalizeCoordinates_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, minLevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxLevel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, anchorScale_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getAspectRatiosList().size();
        size += dataSize;
        size += 1 * getAspectRatiosList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, scalesPerOctave_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, normalizeCoordinates_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator)) {
        return super.equals(obj);
      }
      object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator other = (object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) obj;

      boolean result = true;
      result = result && (hasMinLevel() == other.hasMinLevel());
      if (hasMinLevel()) {
        result = result && (getMinLevel()
            == other.getMinLevel());
      }
      result = result && (hasMaxLevel() == other.hasMaxLevel());
      if (hasMaxLevel()) {
        result = result && (getMaxLevel()
            == other.getMaxLevel());
      }
      result = result && (hasAnchorScale() == other.hasAnchorScale());
      if (hasAnchorScale()) {
        result = result && (
            java.lang.Float.floatToIntBits(getAnchorScale())
            == java.lang.Float.floatToIntBits(
                other.getAnchorScale()));
      }
      result = result && getAspectRatiosList()
          .equals(other.getAspectRatiosList());
      result = result && (hasScalesPerOctave() == other.hasScalesPerOctave());
      if (hasScalesPerOctave()) {
        result = result && (getScalesPerOctave()
            == other.getScalesPerOctave());
      }
      result = result && (hasNormalizeCoordinates() == other.hasNormalizeCoordinates());
      if (hasNormalizeCoordinates()) {
        result = result && (getNormalizeCoordinates()
            == other.getNormalizeCoordinates());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMinLevel()) {
        hash = (37 * hash) + MIN_LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getMinLevel();
      }
      if (hasMaxLevel()) {
        hash = (37 * hash) + MAX_LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getMaxLevel();
      }
      if (hasAnchorScale()) {
        hash = (37 * hash) + ANCHOR_SCALE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getAnchorScale());
      }
      if (getAspectRatiosCount() > 0) {
        hash = (37 * hash) + ASPECT_RATIOS_FIELD_NUMBER;
        hash = (53 * hash) + getAspectRatiosList().hashCode();
      }
      if (hasScalesPerOctave()) {
        hash = (37 * hash) + SCALES_PER_OCTAVE_FIELD_NUMBER;
        hash = (53 * hash) + getScalesPerOctave();
      }
      if (hasNormalizeCoordinates()) {
        hash = (37 * hash) + NORMALIZE_COORDINATES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getNormalizeCoordinates());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration proto for RetinaNet anchor generator described in
     * https://arxiv.org/abs/1708.02002. See
     * anchor_generators/multiscale_grid_anchor_generator.py for details.
     * </pre>
     *
     * Protobuf type {@code object_detection.protos.MultiscaleAnchorGenerator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:object_detection.protos.MultiscaleAnchorGenerator)
        object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGeneratorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.internal_static_object_detection_protos_MultiscaleAnchorGenerator_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.internal_static_object_detection_protos_MultiscaleAnchorGenerator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.class, object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.Builder.class);
      }

      // Construct using object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        minLevel_ = 3;
        bitField0_ = (bitField0_ & ~0x00000001);
        maxLevel_ = 7;
        bitField0_ = (bitField0_ & ~0x00000002);
        anchorScale_ = 4F;
        bitField0_ = (bitField0_ & ~0x00000004);
        aspectRatios_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        scalesPerOctave_ = 2;
        bitField0_ = (bitField0_ & ~0x00000010);
        normalizeCoordinates_ = true;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.internal_static_object_detection_protos_MultiscaleAnchorGenerator_descriptor;
      }

      @java.lang.Override
      public object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator getDefaultInstanceForType() {
        return object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.getDefaultInstance();
      }

      @java.lang.Override
      public object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator build() {
        object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator buildPartial() {
        object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator result = new object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.minLevel_ = minLevel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.maxLevel_ = maxLevel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.anchorScale_ = anchorScale_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          aspectRatios_ = java.util.Collections.unmodifiableList(aspectRatios_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.aspectRatios_ = aspectRatios_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.scalesPerOctave_ = scalesPerOctave_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.normalizeCoordinates_ = normalizeCoordinates_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) {
          return mergeFrom((object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator other) {
        if (other == object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator.getDefaultInstance()) return this;
        if (other.hasMinLevel()) {
          setMinLevel(other.getMinLevel());
        }
        if (other.hasMaxLevel()) {
          setMaxLevel(other.getMaxLevel());
        }
        if (other.hasAnchorScale()) {
          setAnchorScale(other.getAnchorScale());
        }
        if (!other.aspectRatios_.isEmpty()) {
          if (aspectRatios_.isEmpty()) {
            aspectRatios_ = other.aspectRatios_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAspectRatiosIsMutable();
            aspectRatios_.addAll(other.aspectRatios_);
          }
          onChanged();
        }
        if (other.hasScalesPerOctave()) {
          setScalesPerOctave(other.getScalesPerOctave());
        }
        if (other.hasNormalizeCoordinates()) {
          setNormalizeCoordinates(other.getNormalizeCoordinates());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int minLevel_ = 3;
      /**
       * <pre>
       * minimum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       */
      public boolean hasMinLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * minimum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       */
      public int getMinLevel() {
        return minLevel_;
      }
      /**
       * <pre>
       * minimum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       */
      public Builder setMinLevel(int value) {
        bitField0_ |= 0x00000001;
        minLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * minimum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 min_level = 1 [default = 3];</code>
       */
      public Builder clearMinLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        minLevel_ = 3;
        onChanged();
        return this;
      }

      private int maxLevel_ = 7;
      /**
       * <pre>
       * maximum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       */
      public boolean hasMaxLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * maximum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       */
      public int getMaxLevel() {
        return maxLevel_;
      }
      /**
       * <pre>
       * maximum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       */
      public Builder setMaxLevel(int value) {
        bitField0_ |= 0x00000002;
        maxLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * maximum level in feature pyramid
       * </pre>
       *
       * <code>optional int32 max_level = 2 [default = 7];</code>
       */
      public Builder clearMaxLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxLevel_ = 7;
        onChanged();
        return this;
      }

      private float anchorScale_ = 4F;
      /**
       * <pre>
       * Scale of anchor to feature stride
       * </pre>
       *
       * <code>optional float anchor_scale = 3 [default = 4];</code>
       */
      public boolean hasAnchorScale() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * Scale of anchor to feature stride
       * </pre>
       *
       * <code>optional float anchor_scale = 3 [default = 4];</code>
       */
      public float getAnchorScale() {
        return anchorScale_;
      }
      /**
       * <pre>
       * Scale of anchor to feature stride
       * </pre>
       *
       * <code>optional float anchor_scale = 3 [default = 4];</code>
       */
      public Builder setAnchorScale(float value) {
        bitField0_ |= 0x00000004;
        anchorScale_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Scale of anchor to feature stride
       * </pre>
       *
       * <code>optional float anchor_scale = 3 [default = 4];</code>
       */
      public Builder clearAnchorScale() {
        bitField0_ = (bitField0_ & ~0x00000004);
        anchorScale_ = 4F;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> aspectRatios_ = java.util.Collections.emptyList();
      private void ensureAspectRatiosIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          aspectRatios_ = new java.util.ArrayList<java.lang.Float>(aspectRatios_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       * Aspect ratios for anchors at each grid point.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 4;</code>
       */
      public java.util.List<java.lang.Float>
          getAspectRatiosList() {
        return java.util.Collections.unmodifiableList(aspectRatios_);
      }
      /**
       * <pre>
       * Aspect ratios for anchors at each grid point.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 4;</code>
       */
      public int getAspectRatiosCount() {
        return aspectRatios_.size();
      }
      /**
       * <pre>
       * Aspect ratios for anchors at each grid point.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 4;</code>
       */
      public float getAspectRatios(int index) {
        return aspectRatios_.get(index);
      }
      /**
       * <pre>
       * Aspect ratios for anchors at each grid point.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 4;</code>
       */
      public Builder setAspectRatios(
          int index, float value) {
        ensureAspectRatiosIsMutable();
        aspectRatios_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Aspect ratios for anchors at each grid point.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 4;</code>
       */
      public Builder addAspectRatios(float value) {
        ensureAspectRatiosIsMutable();
        aspectRatios_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Aspect ratios for anchors at each grid point.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 4;</code>
       */
      public Builder addAllAspectRatios(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureAspectRatiosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aspectRatios_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Aspect ratios for anchors at each grid point.
       * </pre>
       *
       * <code>repeated float aspect_ratios = 4;</code>
       */
      public Builder clearAspectRatios() {
        aspectRatios_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private int scalesPerOctave_ = 2;
      /**
       * <pre>
       * Number of intermediate scale each scale octave
       * </pre>
       *
       * <code>optional int32 scales_per_octave = 5 [default = 2];</code>
       */
      public boolean hasScalesPerOctave() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * Number of intermediate scale each scale octave
       * </pre>
       *
       * <code>optional int32 scales_per_octave = 5 [default = 2];</code>
       */
      public int getScalesPerOctave() {
        return scalesPerOctave_;
      }
      /**
       * <pre>
       * Number of intermediate scale each scale octave
       * </pre>
       *
       * <code>optional int32 scales_per_octave = 5 [default = 2];</code>
       */
      public Builder setScalesPerOctave(int value) {
        bitField0_ |= 0x00000010;
        scalesPerOctave_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of intermediate scale each scale octave
       * </pre>
       *
       * <code>optional int32 scales_per_octave = 5 [default = 2];</code>
       */
      public Builder clearScalesPerOctave() {
        bitField0_ = (bitField0_ & ~0x00000010);
        scalesPerOctave_ = 2;
        onChanged();
        return this;
      }

      private boolean normalizeCoordinates_ = true;
      /**
       * <pre>
       * Whether to produce anchors in normalized coordinates.
       * </pre>
       *
       * <code>optional bool normalize_coordinates = 6 [default = true];</code>
       */
      public boolean hasNormalizeCoordinates() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * Whether to produce anchors in normalized coordinates.
       * </pre>
       *
       * <code>optional bool normalize_coordinates = 6 [default = true];</code>
       */
      public boolean getNormalizeCoordinates() {
        return normalizeCoordinates_;
      }
      /**
       * <pre>
       * Whether to produce anchors in normalized coordinates.
       * </pre>
       *
       * <code>optional bool normalize_coordinates = 6 [default = true];</code>
       */
      public Builder setNormalizeCoordinates(boolean value) {
        bitField0_ |= 0x00000020;
        normalizeCoordinates_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether to produce anchors in normalized coordinates.
       * </pre>
       *
       * <code>optional bool normalize_coordinates = 6 [default = true];</code>
       */
      public Builder clearNormalizeCoordinates() {
        bitField0_ = (bitField0_ & ~0x00000020);
        normalizeCoordinates_ = true;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:object_detection.protos.MultiscaleAnchorGenerator)
    }

    // @@protoc_insertion_point(class_scope:object_detection.protos.MultiscaleAnchorGenerator)
    private static final object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator();
    }

    public static object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MultiscaleAnchorGenerator>
        PARSER = new com.google.protobuf.AbstractParser<MultiscaleAnchorGenerator>() {
      @java.lang.Override
      public MultiscaleAnchorGenerator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiscaleAnchorGenerator(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiscaleAnchorGenerator> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultiscaleAnchorGenerator> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public object_detection.protos.MultiscaleAnchorGeneratorOuterClass.MultiscaleAnchorGenerator getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_object_detection_protos_MultiscaleAnchorGenerator_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_object_detection_protos_MultiscaleAnchorGenerator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9object_detection/protos/multiscale_anc" +
      "hor_generator.proto\022\027object_detection.pr" +
      "otos\"\272\001\n\031MultiscaleAnchorGenerator\022\024\n\tmi" +
      "n_level\030\001 \001(\005:\0013\022\024\n\tmax_level\030\002 \001(\005:\0017\022\027" +
      "\n\014anchor_scale\030\003 \001(\002:\0014\022\025\n\raspect_ratios" +
      "\030\004 \003(\002\022\034\n\021scales_per_octave\030\005 \001(\005:\0012\022#\n\025" +
      "normalize_coordinates\030\006 \001(\010:\004true"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_object_detection_protos_MultiscaleAnchorGenerator_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_object_detection_protos_MultiscaleAnchorGenerator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_object_detection_protos_MultiscaleAnchorGenerator_descriptor,
        new java.lang.String[] { "MinLevel", "MaxLevel", "AnchorScale", "AspectRatios", "ScalesPerOctave", "NormalizeCoordinates", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
