/*
 * Copyright (c) 2019. Kin-Hong Wong. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ==============================================================================
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/square_box_coder.proto

package object_detection.protos;

public final class SquareBoxCoderOuterClass {
  private SquareBoxCoderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SquareBoxCoderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:object_detection.protos.SquareBoxCoder)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Scale factor for anchor encoded box center.
     * </pre>
     *
     * <code>optional float y_scale = 1 [default = 10];</code>
     */
    boolean hasYScale();
    /**
     * <pre>
     * Scale factor for anchor encoded box center.
     * </pre>
     *
     * <code>optional float y_scale = 1 [default = 10];</code>
     */
    float getYScale();

    /**
     * <code>optional float x_scale = 2 [default = 10];</code>
     */
    boolean hasXScale();
    /**
     * <code>optional float x_scale = 2 [default = 10];</code>
     */
    float getXScale();

    /**
     * <pre>
     * Scale factor for anchor encoded box length.
     * </pre>
     *
     * <code>optional float length_scale = 3 [default = 5];</code>
     */
    boolean hasLengthScale();
    /**
     * <pre>
     * Scale factor for anchor encoded box length.
     * </pre>
     *
     * <code>optional float length_scale = 3 [default = 5];</code>
     */
    float getLengthScale();
  }
  /**
   * <pre>
   * Configuration proto for SquareBoxCoder. See
   * box_coders/square_box_coder.py for details.
   * </pre>
   *
   * Protobuf type {@code object_detection.protos.SquareBoxCoder}
   */
  public  static final class SquareBoxCoder extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:object_detection.protos.SquareBoxCoder)
      SquareBoxCoderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SquareBoxCoder.newBuilder() to construct.
    private SquareBoxCoder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SquareBoxCoder() {
      yScale_ = 10F;
      xScale_ = 10F;
      lengthScale_ = 5F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SquareBoxCoder(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              bitField0_ |= 0x00000001;
              yScale_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              xScale_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              lengthScale_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return object_detection.protos.SquareBoxCoderOuterClass.internal_static_object_detection_protos_SquareBoxCoder_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return object_detection.protos.SquareBoxCoderOuterClass.internal_static_object_detection_protos_SquareBoxCoder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.class, object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.Builder.class);
    }

    private int bitField0_;
    public static final int Y_SCALE_FIELD_NUMBER = 1;
    private float yScale_;
    /**
     * <pre>
     * Scale factor for anchor encoded box center.
     * </pre>
     *
     * <code>optional float y_scale = 1 [default = 10];</code>
     */
    public boolean hasYScale() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * Scale factor for anchor encoded box center.
     * </pre>
     *
     * <code>optional float y_scale = 1 [default = 10];</code>
     */
    public float getYScale() {
      return yScale_;
    }

    public static final int X_SCALE_FIELD_NUMBER = 2;
    private float xScale_;
    /**
     * <code>optional float x_scale = 2 [default = 10];</code>
     */
    public boolean hasXScale() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float x_scale = 2 [default = 10];</code>
     */
    public float getXScale() {
      return xScale_;
    }

    public static final int LENGTH_SCALE_FIELD_NUMBER = 3;
    private float lengthScale_;
    /**
     * <pre>
     * Scale factor for anchor encoded box length.
     * </pre>
     *
     * <code>optional float length_scale = 3 [default = 5];</code>
     */
    public boolean hasLengthScale() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Scale factor for anchor encoded box length.
     * </pre>
     *
     * <code>optional float length_scale = 3 [default = 5];</code>
     */
    public float getLengthScale() {
      return lengthScale_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, yScale_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, xScale_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, lengthScale_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, yScale_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, xScale_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, lengthScale_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder)) {
        return super.equals(obj);
      }
      object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder other = (object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) obj;

      boolean result = true;
      result = result && (hasYScale() == other.hasYScale());
      if (hasYScale()) {
        result = result && (
            java.lang.Float.floatToIntBits(getYScale())
            == java.lang.Float.floatToIntBits(
                other.getYScale()));
      }
      result = result && (hasXScale() == other.hasXScale());
      if (hasXScale()) {
        result = result && (
            java.lang.Float.floatToIntBits(getXScale())
            == java.lang.Float.floatToIntBits(
                other.getXScale()));
      }
      result = result && (hasLengthScale() == other.hasLengthScale());
      if (hasLengthScale()) {
        result = result && (
            java.lang.Float.floatToIntBits(getLengthScale())
            == java.lang.Float.floatToIntBits(
                other.getLengthScale()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasYScale()) {
        hash = (37 * hash) + Y_SCALE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getYScale());
      }
      if (hasXScale()) {
        hash = (37 * hash) + X_SCALE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getXScale());
      }
      if (hasLengthScale()) {
        hash = (37 * hash) + LENGTH_SCALE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLengthScale());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration proto for SquareBoxCoder. See
     * box_coders/square_box_coder.py for details.
     * </pre>
     *
     * Protobuf type {@code object_detection.protos.SquareBoxCoder}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:object_detection.protos.SquareBoxCoder)
        object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return object_detection.protos.SquareBoxCoderOuterClass.internal_static_object_detection_protos_SquareBoxCoder_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return object_detection.protos.SquareBoxCoderOuterClass.internal_static_object_detection_protos_SquareBoxCoder_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.class, object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.Builder.class);
      }

      // Construct using object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        yScale_ = 10F;
        bitField0_ = (bitField0_ & ~0x00000001);
        xScale_ = 10F;
        bitField0_ = (bitField0_ & ~0x00000002);
        lengthScale_ = 5F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return object_detection.protos.SquareBoxCoderOuterClass.internal_static_object_detection_protos_SquareBoxCoder_descriptor;
      }

      @java.lang.Override
      public object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder getDefaultInstanceForType() {
        return object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.getDefaultInstance();
      }

      @java.lang.Override
      public object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder build() {
        object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder buildPartial() {
        object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder result = new object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.yScale_ = yScale_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.xScale_ = xScale_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lengthScale_ = lengthScale_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) {
          return mergeFrom((object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder other) {
        if (other == object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder.getDefaultInstance()) return this;
        if (other.hasYScale()) {
          setYScale(other.getYScale());
        }
        if (other.hasXScale()) {
          setXScale(other.getXScale());
        }
        if (other.hasLengthScale()) {
          setLengthScale(other.getLengthScale());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float yScale_ = 10F;
      /**
       * <pre>
       * Scale factor for anchor encoded box center.
       * </pre>
       *
       * <code>optional float y_scale = 1 [default = 10];</code>
       */
      public boolean hasYScale() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * Scale factor for anchor encoded box center.
       * </pre>
       *
       * <code>optional float y_scale = 1 [default = 10];</code>
       */
      public float getYScale() {
        return yScale_;
      }
      /**
       * <pre>
       * Scale factor for anchor encoded box center.
       * </pre>
       *
       * <code>optional float y_scale = 1 [default = 10];</code>
       */
      public Builder setYScale(float value) {
        bitField0_ |= 0x00000001;
        yScale_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Scale factor for anchor encoded box center.
       * </pre>
       *
       * <code>optional float y_scale = 1 [default = 10];</code>
       */
      public Builder clearYScale() {
        bitField0_ = (bitField0_ & ~0x00000001);
        yScale_ = 10F;
        onChanged();
        return this;
      }

      private float xScale_ = 10F;
      /**
       * <code>optional float x_scale = 2 [default = 10];</code>
       */
      public boolean hasXScale() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float x_scale = 2 [default = 10];</code>
       */
      public float getXScale() {
        return xScale_;
      }
      /**
       * <code>optional float x_scale = 2 [default = 10];</code>
       */
      public Builder setXScale(float value) {
        bitField0_ |= 0x00000002;
        xScale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float x_scale = 2 [default = 10];</code>
       */
      public Builder clearXScale() {
        bitField0_ = (bitField0_ & ~0x00000002);
        xScale_ = 10F;
        onChanged();
        return this;
      }

      private float lengthScale_ = 5F;
      /**
       * <pre>
       * Scale factor for anchor encoded box length.
       * </pre>
       *
       * <code>optional float length_scale = 3 [default = 5];</code>
       */
      public boolean hasLengthScale() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * Scale factor for anchor encoded box length.
       * </pre>
       *
       * <code>optional float length_scale = 3 [default = 5];</code>
       */
      public float getLengthScale() {
        return lengthScale_;
      }
      /**
       * <pre>
       * Scale factor for anchor encoded box length.
       * </pre>
       *
       * <code>optional float length_scale = 3 [default = 5];</code>
       */
      public Builder setLengthScale(float value) {
        bitField0_ |= 0x00000004;
        lengthScale_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Scale factor for anchor encoded box length.
       * </pre>
       *
       * <code>optional float length_scale = 3 [default = 5];</code>
       */
      public Builder clearLengthScale() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lengthScale_ = 5F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:object_detection.protos.SquareBoxCoder)
    }

    // @@protoc_insertion_point(class_scope:object_detection.protos.SquareBoxCoder)
    private static final object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder();
    }

    public static object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SquareBoxCoder>
        PARSER = new com.google.protobuf.AbstractParser<SquareBoxCoder>() {
      @java.lang.Override
      public SquareBoxCoder parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SquareBoxCoder(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SquareBoxCoder> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SquareBoxCoder> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public object_detection.protos.SquareBoxCoderOuterClass.SquareBoxCoder getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_object_detection_protos_SquareBoxCoder_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_object_detection_protos_SquareBoxCoder_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.object_detection/protos/square_box_cod" +
      "er.proto\022\027object_detection.protos\"S\n\016Squ" +
      "areBoxCoder\022\023\n\007y_scale\030\001 \001(\002:\00210\022\023\n\007x_sc" +
      "ale\030\002 \001(\002:\00210\022\027\n\014length_scale\030\003 \001(\002:\0015"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_object_detection_protos_SquareBoxCoder_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_object_detection_protos_SquareBoxCoder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_object_detection_protos_SquareBoxCoder_descriptor,
        new java.lang.String[] { "YScale", "XScale", "LengthScale", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
