/*
 * Copyright (c) 2020. Kin-Hong Wong. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/target_assigner.proto

package object_detection.protos;

public final class TargetAssignerOuterClass {
  private TargetAssignerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TargetAssignerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:object_detection.protos.TargetAssigner)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
     * @return Whether the matcher field is set.
     */
    boolean hasMatcher();
    /**
     * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
     * @return The matcher.
     */
    object_detection.protos.MatcherOuterClass.Matcher getMatcher();
    /**
     * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
     */
    object_detection.protos.MatcherOuterClass.MatcherOrBuilder getMatcherOrBuilder();

    /**
     * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
     * @return Whether the similarityCalculator field is set.
     */
    boolean hasSimilarityCalculator();
    /**
     * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
     * @return The similarityCalculator.
     */
    object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator getSimilarityCalculator();
    /**
     * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
     */
    object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculatorOrBuilder getSimilarityCalculatorOrBuilder();

    /**
     * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
     * @return Whether the boxCoder field is set.
     */
    boolean hasBoxCoder();
    /**
     * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
     * @return The boxCoder.
     */
    object_detection.protos.BoxCoderOuterClass.BoxCoder getBoxCoder();
    /**
     * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
     */
    object_detection.protos.BoxCoderOuterClass.BoxCoderOrBuilder getBoxCoderOrBuilder();
  }
  /**
   * <pre>
   * Message to configure Target Assigner for object detectors.
   * </pre>
   *
   * Protobuf type {@code object_detection.protos.TargetAssigner}
   */
  public static final class TargetAssigner extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:object_detection.protos.TargetAssigner)
      TargetAssignerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TargetAssigner.newBuilder() to construct.
    private TargetAssigner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TargetAssigner() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TargetAssigner();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TargetAssigner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              object_detection.protos.MatcherOuterClass.Matcher.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = matcher_.toBuilder();
              }
              matcher_ = input.readMessage(object_detection.protos.MatcherOuterClass.Matcher.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(matcher_);
                matcher_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = similarityCalculator_.toBuilder();
              }
              similarityCalculator_ = input.readMessage(object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(similarityCalculator_);
                similarityCalculator_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              object_detection.protos.BoxCoderOuterClass.BoxCoder.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = boxCoder_.toBuilder();
              }
              boxCoder_ = input.readMessage(object_detection.protos.BoxCoderOuterClass.BoxCoder.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(boxCoder_);
                boxCoder_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return object_detection.protos.TargetAssignerOuterClass.internal_static_object_detection_protos_TargetAssigner_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return object_detection.protos.TargetAssignerOuterClass.internal_static_object_detection_protos_TargetAssigner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              object_detection.protos.TargetAssignerOuterClass.TargetAssigner.class, object_detection.protos.TargetAssignerOuterClass.TargetAssigner.Builder.class);
    }

    private int bitField0_;
    public static final int MATCHER_FIELD_NUMBER = 1;
    private object_detection.protos.MatcherOuterClass.Matcher matcher_;
    /**
     * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
     * @return Whether the matcher field is set.
     */
    @java.lang.Override
    public boolean hasMatcher() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
     * @return The matcher.
     */
    @java.lang.Override
    public object_detection.protos.MatcherOuterClass.Matcher getMatcher() {
      return matcher_ == null ? object_detection.protos.MatcherOuterClass.Matcher.getDefaultInstance() : matcher_;
    }
    /**
     * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
     */
    @java.lang.Override
    public object_detection.protos.MatcherOuterClass.MatcherOrBuilder getMatcherOrBuilder() {
      return matcher_ == null ? object_detection.protos.MatcherOuterClass.Matcher.getDefaultInstance() : matcher_;
    }

    public static final int SIMILARITY_CALCULATOR_FIELD_NUMBER = 2;
    private object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator similarityCalculator_;
    /**
     * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
     * @return Whether the similarityCalculator field is set.
     */
    @java.lang.Override
    public boolean hasSimilarityCalculator() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
     * @return The similarityCalculator.
     */
    @java.lang.Override
    public object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator getSimilarityCalculator() {
      return similarityCalculator_ == null ? object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.getDefaultInstance() : similarityCalculator_;
    }
    /**
     * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
     */
    @java.lang.Override
    public object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculatorOrBuilder getSimilarityCalculatorOrBuilder() {
      return similarityCalculator_ == null ? object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.getDefaultInstance() : similarityCalculator_;
    }

    public static final int BOX_CODER_FIELD_NUMBER = 3;
    private object_detection.protos.BoxCoderOuterClass.BoxCoder boxCoder_;
    /**
     * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
     * @return Whether the boxCoder field is set.
     */
    @java.lang.Override
    public boolean hasBoxCoder() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
     * @return The boxCoder.
     */
    @java.lang.Override
    public object_detection.protos.BoxCoderOuterClass.BoxCoder getBoxCoder() {
      return boxCoder_ == null ? object_detection.protos.BoxCoderOuterClass.BoxCoder.getDefaultInstance() : boxCoder_;
    }
    /**
     * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
     */
    @java.lang.Override
    public object_detection.protos.BoxCoderOuterClass.BoxCoderOrBuilder getBoxCoderOrBuilder() {
      return boxCoder_ == null ? object_detection.protos.BoxCoderOuterClass.BoxCoder.getDefaultInstance() : boxCoder_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getMatcher());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getSimilarityCalculator());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getBoxCoder());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMatcher());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSimilarityCalculator());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBoxCoder());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof object_detection.protos.TargetAssignerOuterClass.TargetAssigner)) {
        return super.equals(obj);
      }
      object_detection.protos.TargetAssignerOuterClass.TargetAssigner other = (object_detection.protos.TargetAssignerOuterClass.TargetAssigner) obj;

      if (hasMatcher() != other.hasMatcher()) return false;
      if (hasMatcher()) {
        if (!getMatcher()
            .equals(other.getMatcher())) return false;
      }
      if (hasSimilarityCalculator() != other.hasSimilarityCalculator()) return false;
      if (hasSimilarityCalculator()) {
        if (!getSimilarityCalculator()
            .equals(other.getSimilarityCalculator())) return false;
      }
      if (hasBoxCoder() != other.hasBoxCoder()) return false;
      if (hasBoxCoder()) {
        if (!getBoxCoder()
            .equals(other.getBoxCoder())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMatcher()) {
        hash = (37 * hash) + MATCHER_FIELD_NUMBER;
        hash = (53 * hash) + getMatcher().hashCode();
      }
      if (hasSimilarityCalculator()) {
        hash = (37 * hash) + SIMILARITY_CALCULATOR_FIELD_NUMBER;
        hash = (53 * hash) + getSimilarityCalculator().hashCode();
      }
      if (hasBoxCoder()) {
        hash = (37 * hash) + BOX_CODER_FIELD_NUMBER;
        hash = (53 * hash) + getBoxCoder().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(object_detection.protos.TargetAssignerOuterClass.TargetAssigner prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message to configure Target Assigner for object detectors.
     * </pre>
     *
     * Protobuf type {@code object_detection.protos.TargetAssigner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:object_detection.protos.TargetAssigner)
        object_detection.protos.TargetAssignerOuterClass.TargetAssignerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return object_detection.protos.TargetAssignerOuterClass.internal_static_object_detection_protos_TargetAssigner_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return object_detection.protos.TargetAssignerOuterClass.internal_static_object_detection_protos_TargetAssigner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                object_detection.protos.TargetAssignerOuterClass.TargetAssigner.class, object_detection.protos.TargetAssignerOuterClass.TargetAssigner.Builder.class);
      }

      // Construct using object_detection.protos.TargetAssignerOuterClass.TargetAssigner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMatcherFieldBuilder();
          getSimilarityCalculatorFieldBuilder();
          getBoxCoderFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (matcherBuilder_ == null) {
          matcher_ = null;
        } else {
          matcherBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (similarityCalculatorBuilder_ == null) {
          similarityCalculator_ = null;
        } else {
          similarityCalculatorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (boxCoderBuilder_ == null) {
          boxCoder_ = null;
        } else {
          boxCoderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return object_detection.protos.TargetAssignerOuterClass.internal_static_object_detection_protos_TargetAssigner_descriptor;
      }

      @java.lang.Override
      public object_detection.protos.TargetAssignerOuterClass.TargetAssigner getDefaultInstanceForType() {
        return object_detection.protos.TargetAssignerOuterClass.TargetAssigner.getDefaultInstance();
      }

      @java.lang.Override
      public object_detection.protos.TargetAssignerOuterClass.TargetAssigner build() {
        object_detection.protos.TargetAssignerOuterClass.TargetAssigner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public object_detection.protos.TargetAssignerOuterClass.TargetAssigner buildPartial() {
        object_detection.protos.TargetAssignerOuterClass.TargetAssigner result = new object_detection.protos.TargetAssignerOuterClass.TargetAssigner(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (matcherBuilder_ == null) {
            result.matcher_ = matcher_;
          } else {
            result.matcher_ = matcherBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (similarityCalculatorBuilder_ == null) {
            result.similarityCalculator_ = similarityCalculator_;
          } else {
            result.similarityCalculator_ = similarityCalculatorBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (boxCoderBuilder_ == null) {
            result.boxCoder_ = boxCoder_;
          } else {
            result.boxCoder_ = boxCoderBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof object_detection.protos.TargetAssignerOuterClass.TargetAssigner) {
          return mergeFrom((object_detection.protos.TargetAssignerOuterClass.TargetAssigner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(object_detection.protos.TargetAssignerOuterClass.TargetAssigner other) {
        if (other == object_detection.protos.TargetAssignerOuterClass.TargetAssigner.getDefaultInstance()) return this;
        if (other.hasMatcher()) {
          mergeMatcher(other.getMatcher());
        }
        if (other.hasSimilarityCalculator()) {
          mergeSimilarityCalculator(other.getSimilarityCalculator());
        }
        if (other.hasBoxCoder()) {
          mergeBoxCoder(other.getBoxCoder());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        object_detection.protos.TargetAssignerOuterClass.TargetAssigner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (object_detection.protos.TargetAssignerOuterClass.TargetAssigner) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private object_detection.protos.MatcherOuterClass.Matcher matcher_;
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.MatcherOuterClass.Matcher, object_detection.protos.MatcherOuterClass.Matcher.Builder, object_detection.protos.MatcherOuterClass.MatcherOrBuilder> matcherBuilder_;
      /**
       * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
       * @return Whether the matcher field is set.
       */
      public boolean hasMatcher() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
       * @return The matcher.
       */
      public object_detection.protos.MatcherOuterClass.Matcher getMatcher() {
        if (matcherBuilder_ == null) {
          return matcher_ == null ? object_detection.protos.MatcherOuterClass.Matcher.getDefaultInstance() : matcher_;
        } else {
          return matcherBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
       */
      public Builder setMatcher(object_detection.protos.MatcherOuterClass.Matcher value) {
        if (matcherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          matcher_ = value;
          onChanged();
        } else {
          matcherBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
       */
      public Builder setMatcher(
          object_detection.protos.MatcherOuterClass.Matcher.Builder builderForValue) {
        if (matcherBuilder_ == null) {
          matcher_ = builderForValue.build();
          onChanged();
        } else {
          matcherBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
       */
      public Builder mergeMatcher(object_detection.protos.MatcherOuterClass.Matcher value) {
        if (matcherBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              matcher_ != null &&
              matcher_ != object_detection.protos.MatcherOuterClass.Matcher.getDefaultInstance()) {
            matcher_ =
              object_detection.protos.MatcherOuterClass.Matcher.newBuilder(matcher_).mergeFrom(value).buildPartial();
          } else {
            matcher_ = value;
          }
          onChanged();
        } else {
          matcherBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
       */
      public Builder clearMatcher() {
        if (matcherBuilder_ == null) {
          matcher_ = null;
          onChanged();
        } else {
          matcherBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
       */
      public object_detection.protos.MatcherOuterClass.Matcher.Builder getMatcherBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMatcherFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
       */
      public object_detection.protos.MatcherOuterClass.MatcherOrBuilder getMatcherOrBuilder() {
        if (matcherBuilder_ != null) {
          return matcherBuilder_.getMessageOrBuilder();
        } else {
          return matcher_ == null ?
              object_detection.protos.MatcherOuterClass.Matcher.getDefaultInstance() : matcher_;
        }
      }
      /**
       * <code>optional .object_detection.protos.Matcher matcher = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.MatcherOuterClass.Matcher, object_detection.protos.MatcherOuterClass.Matcher.Builder, object_detection.protos.MatcherOuterClass.MatcherOrBuilder>
          getMatcherFieldBuilder() {
        if (matcherBuilder_ == null) {
          matcherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.MatcherOuterClass.Matcher, object_detection.protos.MatcherOuterClass.Matcher.Builder, object_detection.protos.MatcherOuterClass.MatcherOrBuilder>(
                  getMatcher(),
                  getParentForChildren(),
                  isClean());
          matcher_ = null;
        }
        return matcherBuilder_;
      }

      private object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator similarityCalculator_;
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator, object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.Builder, object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculatorOrBuilder> similarityCalculatorBuilder_;
      /**
       * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
       * @return Whether the similarityCalculator field is set.
       */
      public boolean hasSimilarityCalculator() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
       * @return The similarityCalculator.
       */
      public object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator getSimilarityCalculator() {
        if (similarityCalculatorBuilder_ == null) {
          return similarityCalculator_ == null ? object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.getDefaultInstance() : similarityCalculator_;
        } else {
          return similarityCalculatorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
       */
      public Builder setSimilarityCalculator(object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator value) {
        if (similarityCalculatorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          similarityCalculator_ = value;
          onChanged();
        } else {
          similarityCalculatorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
       */
      public Builder setSimilarityCalculator(
          object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.Builder builderForValue) {
        if (similarityCalculatorBuilder_ == null) {
          similarityCalculator_ = builderForValue.build();
          onChanged();
        } else {
          similarityCalculatorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
       */
      public Builder mergeSimilarityCalculator(object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator value) {
        if (similarityCalculatorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              similarityCalculator_ != null &&
              similarityCalculator_ != object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.getDefaultInstance()) {
            similarityCalculator_ =
              object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.newBuilder(similarityCalculator_).mergeFrom(value).buildPartial();
          } else {
            similarityCalculator_ = value;
          }
          onChanged();
        } else {
          similarityCalculatorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
       */
      public Builder clearSimilarityCalculator() {
        if (similarityCalculatorBuilder_ == null) {
          similarityCalculator_ = null;
          onChanged();
        } else {
          similarityCalculatorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
       */
      public object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.Builder getSimilarityCalculatorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSimilarityCalculatorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
       */
      public object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculatorOrBuilder getSimilarityCalculatorOrBuilder() {
        if (similarityCalculatorBuilder_ != null) {
          return similarityCalculatorBuilder_.getMessageOrBuilder();
        } else {
          return similarityCalculator_ == null ?
              object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.getDefaultInstance() : similarityCalculator_;
        }
      }
      /**
       * <code>optional .object_detection.protos.RegionSimilarityCalculator similarity_calculator = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator, object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.Builder, object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculatorOrBuilder>
          getSimilarityCalculatorFieldBuilder() {
        if (similarityCalculatorBuilder_ == null) {
          similarityCalculatorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator, object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculator.Builder, object_detection.protos.RegionSimilarityCalculatorOuterClass.RegionSimilarityCalculatorOrBuilder>(
                  getSimilarityCalculator(),
                  getParentForChildren(),
                  isClean());
          similarityCalculator_ = null;
        }
        return similarityCalculatorBuilder_;
      }

      private object_detection.protos.BoxCoderOuterClass.BoxCoder boxCoder_;
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.BoxCoderOuterClass.BoxCoder, object_detection.protos.BoxCoderOuterClass.BoxCoder.Builder, object_detection.protos.BoxCoderOuterClass.BoxCoderOrBuilder> boxCoderBuilder_;
      /**
       * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
       * @return Whether the boxCoder field is set.
       */
      public boolean hasBoxCoder() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
       * @return The boxCoder.
       */
      public object_detection.protos.BoxCoderOuterClass.BoxCoder getBoxCoder() {
        if (boxCoderBuilder_ == null) {
          return boxCoder_ == null ? object_detection.protos.BoxCoderOuterClass.BoxCoder.getDefaultInstance() : boxCoder_;
        } else {
          return boxCoderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
       */
      public Builder setBoxCoder(object_detection.protos.BoxCoderOuterClass.BoxCoder value) {
        if (boxCoderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          boxCoder_ = value;
          onChanged();
        } else {
          boxCoderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
       */
      public Builder setBoxCoder(
          object_detection.protos.BoxCoderOuterClass.BoxCoder.Builder builderForValue) {
        if (boxCoderBuilder_ == null) {
          boxCoder_ = builderForValue.build();
          onChanged();
        } else {
          boxCoderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
       */
      public Builder mergeBoxCoder(object_detection.protos.BoxCoderOuterClass.BoxCoder value) {
        if (boxCoderBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              boxCoder_ != null &&
              boxCoder_ != object_detection.protos.BoxCoderOuterClass.BoxCoder.getDefaultInstance()) {
            boxCoder_ =
              object_detection.protos.BoxCoderOuterClass.BoxCoder.newBuilder(boxCoder_).mergeFrom(value).buildPartial();
          } else {
            boxCoder_ = value;
          }
          onChanged();
        } else {
          boxCoderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
       */
      public Builder clearBoxCoder() {
        if (boxCoderBuilder_ == null) {
          boxCoder_ = null;
          onChanged();
        } else {
          boxCoderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
       */
      public object_detection.protos.BoxCoderOuterClass.BoxCoder.Builder getBoxCoderBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getBoxCoderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
       */
      public object_detection.protos.BoxCoderOuterClass.BoxCoderOrBuilder getBoxCoderOrBuilder() {
        if (boxCoderBuilder_ != null) {
          return boxCoderBuilder_.getMessageOrBuilder();
        } else {
          return boxCoder_ == null ?
              object_detection.protos.BoxCoderOuterClass.BoxCoder.getDefaultInstance() : boxCoder_;
        }
      }
      /**
       * <code>optional .object_detection.protos.BoxCoder box_coder = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.BoxCoderOuterClass.BoxCoder, object_detection.protos.BoxCoderOuterClass.BoxCoder.Builder, object_detection.protos.BoxCoderOuterClass.BoxCoderOrBuilder>
          getBoxCoderFieldBuilder() {
        if (boxCoderBuilder_ == null) {
          boxCoderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.BoxCoderOuterClass.BoxCoder, object_detection.protos.BoxCoderOuterClass.BoxCoder.Builder, object_detection.protos.BoxCoderOuterClass.BoxCoderOrBuilder>(
                  getBoxCoder(),
                  getParentForChildren(),
                  isClean());
          boxCoder_ = null;
        }
        return boxCoderBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:object_detection.protos.TargetAssigner)
    }

    // @@protoc_insertion_point(class_scope:object_detection.protos.TargetAssigner)
    private static final object_detection.protos.TargetAssignerOuterClass.TargetAssigner DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new object_detection.protos.TargetAssignerOuterClass.TargetAssigner();
    }

    public static object_detection.protos.TargetAssignerOuterClass.TargetAssigner getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TargetAssigner>
        PARSER = new com.google.protobuf.AbstractParser<TargetAssigner>() {
      @java.lang.Override
      public TargetAssigner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TargetAssigner(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TargetAssigner> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TargetAssigner> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public object_detection.protos.TargetAssignerOuterClass.TargetAssigner getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_object_detection_protos_TargetAssigner_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_object_detection_protos_TargetAssigner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-object_detection/protos/target_assigne" +
      "r.proto\022\027object_detection.protos\032\'object" +
      "_detection/protos/box_coder.proto\032%objec" +
      "t_detection/protos/matcher.proto\032:object" +
      "_detection/protos/region_similarity_calc" +
      "ulator.proto\"\315\001\n\016TargetAssigner\0221\n\007match" +
      "er\030\001 \001(\0132 .object_detection.protos.Match" +
      "er\022R\n\025similarity_calculator\030\002 \001(\01323.obje" +
      "ct_detection.protos.RegionSimilarityCalc" +
      "ulator\0224\n\tbox_coder\030\003 \001(\0132!.object_detec" +
      "tion.protos.BoxCoder"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          object_detection.protos.BoxCoderOuterClass.getDescriptor(),
          object_detection.protos.MatcherOuterClass.getDescriptor(),
          object_detection.protos.RegionSimilarityCalculatorOuterClass.getDescriptor(),
        });
    internal_static_object_detection_protos_TargetAssigner_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_object_detection_protos_TargetAssigner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_object_detection_protos_TargetAssigner_descriptor,
        new java.lang.String[] { "Matcher", "SimilarityCalculator", "BoxCoder", });
    object_detection.protos.BoxCoderOuterClass.getDescriptor();
    object_detection.protos.MatcherOuterClass.getDescriptor();
    object_detection.protos.RegionSimilarityCalculatorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
